### ISSUE TITLE
In VS code，The maximum length of the AI answer should be about 1388 words.

### ISSUE THREAD

**Issue by itweblin** [gitbito/bitoai#10]

**Comment by bitomukesh** [comment]
Hi, can you say a bit more about this? Why 1388 words?

**Comment by itweblin** [comment]
Sorry, here's the thing. For example, ask the question 'Show more than 2000 words'. Sometime the return is incomplete, as if truncated.

**Comment by bitoandy** [comment]
We are working on increasing the token limits on our end which are utilized for generating output as well as working on utilizing latest GPT 4 which allows higher token limits. 
Will update once the changes go live on our server side.
