### ISSUE TITLE
The version 1.1.0 does not work well on Android Studio

### ISSUE THREAD

**Issue by zhangjianhd** [gitbito/bitoai#101]
The version 1.1.0 does not work well on Android Studio (Flamingo | 2022.2.1 Patch 2). The input box does not allow Chinese characters to be entered, and the "Backspace" key does not function properly. It seems like the input box is unable to receive focus. I hope this issue can be fixed soon. Thank you.

**Comment by zhangjianhd** [comment]
This Android Studio is based on IDEA 2022.2.1, so it seems to have compatibility issues with IDEA because IDEA 2022.2 does not work either.

**Comment by zhangjianhd** [comment]
I have temporarily rolled back to version 1.0.138, and it is functioning properly

**Comment by nisha-bito** [comment]
hi @zhangjianhd ,

Can you download version 1.1.1 and test if its works for you ? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @zhangjianhd ,

Can you download version 1.1.2 and test if its works for you ?
Please note, this ticket will be auto closed in few days, please feel free to create a new ticket in case the problem still exists.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @zhangjianhd ,

This ticket will be closed now. Feel free to create new ticket if come across any further issues.

Thanks,
Nisha
