### ISSUE TITLE
In vscode,[Insert changes]button not working

### ISSUE THREAD

**Issue by 826327700** [gitbito/bitoai#103]
![image](https://github.com/gitbito/bitoai/assets/23014381/cb4d853b-7c56-464c-baaa-b83e35d64a26)

I opened two TS projects, A and B. The "insert changes" button in project A did not working, while it worked fine in project B. This is quite confusing to me.

**Comment by bitoandy** [comment]
Thanks @826327700 , for reporting the issue, team is looking into this and we will provide an update.

**Comment by monicfenga** [comment]
试试按复制按钮？然后粘贴到编辑器里
try copy button? click copy button, then paste it on the editor

**Comment by nisha-bito** [comment]
hi @826327700 ,

Can you please provide more details :
1. VS code version 
2. Are you using Jupyter notebook ? **Please note**: Bito is not fully supported in Jupyter notebook for File operation like, opening diff view, Copy/paste and Insert. 
3. OS 
4. Bito Version 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @826327700 ,

Please provide required information for us to debug the issue further.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @826327700 ,

Please provide us with more information, in order to debug it further. 
In absence of the input, this ticket will be closed after few days, please feel free to create a new issue, if you face any further errors.

Thanks,
Nisha
