### ISSUE TITLE
It doesn't work and no items in the plug-in

### ISSUE THREAD

**Issue by peterlee808** [gitbito/bitoai#105]
Hi Team,
After installation of the bito plug-in, I'm not able to see anything on the bito plug-in page. Please refer to the attached screenshot.
<img width="344" alt="bito" src="https://github.com/gitbito/bitoai/assets/10989979/7f2b2277-37ff-4c93-a0e4-d0f191a17c08">

**Comment by peterlee808** [comment]
By the way, I installed the plug-in in IntelliJ IDEA 2013.1.3 on Windows system.

**Comment by bitoandy** [comment]
Thanks @peterlee808 , for letting us know about the issue, we are analyzing the issue on our end, will keep you posted. Just to double check you are using Bito IDE version 1.1.1

**Comment by peterlee808** [comment]
Yes. the version is 1.1.1
![image](https://github.com/gitbito/bitoai/assets/10989979/a4a52983-94fa-41d3-880f-2662d73483ef)

**Comment by peterlee808** [comment]
Hi Team,
Do you have any update?

**Comment by nisha-bito** [comment]
hi @peterlee808 ,

Can you please share more details as below for us to analyze it further. 
1. OS 
2. Are you using Java 8 ? 
3. IntelliJ IDEA 2013.1.3 -> i guess its 2023.1.3, please confirm. 
4. Can you share Logs by going to Help -> Show logs in Finder -> and share idea.log 
![image](https://github.com/gitbito/bitoai/assets/123052606/c2b1999a-3dbb-423f-af3b-1ad5621e0e28)

5. Can you also share the console log 
    - Install Bito 
    - Open Bito panel 
    - Go to Help -> Find Action -> Type Bito: open dev tool 
![image](https://github.com/gitbito/bitoai/assets/123052606/0ecf92cf-07f7-4b4c-9aa8-c2ce654f9839)

    - go to console 
    - copy console log and send it to us 
![image](https://github.com/gitbito/bitoai/assets/123052606/cb334b42-8adc-4522-b8db-1db13f48e204)

    - Filter the console log to only show errors and share the error logs with us. 
![image](https://github.com/gitbito/bitoai/assets/123052606/0cc6412d-fad0-4835-b060-443c85fc64b8)


Thanks,
Nisha

**Comment by AlexusYT** [comment]
Hi, @nisha-bito I have the same issue. I checked dev tools window at "Network" tab and saw that only one HTTP request was executed. This request failed with the error "(failed)net::ERR_NAME_NOT_RESOLVED". The request address was http://ideapp/index.html?productName=CLion 2023.2 EAP&parentIdeName=JB&uId=<REDACTED>&userLoginStatus=ws&bitoVersion=1.1.1&theme=dark&fontSize=14&fontFamily=Inter Regular. 
After reenabling the plugin, it works correctly until IDE restarts.
IDE info: CLion 2023.2 EAP Build #CL-232.8660.8, built on July 5, 2023
Bito: 1.1.1
OS: Ubuntu 22.10

**Comment by nisha-bito** [comment]
hi @AlexusYT ,

Are you using any proxy ? 

Thanks,
Nisha

**Comment by AlexusYT** [comment]
@nisha-bito no. I think that after restarting the IDE, the plugin tries to communicate with server using HTTP instead of WebSocket

**Comment by nisha-bito** [comment]
hi @AlexusYT,

 Can you share all the required logs asked in previous comment ? 

Thanks,
Nisha

**Comment by AlexusYT** [comment]
@nisha-bito Hi, sorry for long response. Here is the logs after enabling the plugin:
![image](https://github.com/gitbito/bitoai/assets/93870232/83616d7f-efa4-4f1b-a6bd-aa3c317e466d)
[clion-logs-20230724-1537509316154562383735026.zip](https://github.com/gitbito/bitoai/files/12144837/clion-logs-20230724-1537509316154562383735026.zip)
And here the logs after IDE restart:
![image](https://github.com/gitbito/bitoai/assets/93870232/17023365-ca31-442d-bf4e-021803c04097)
![image](https://github.com/gitbito/bitoai/assets/93870232/e526e695-09fb-41f0-b112-826adf64067f)
[clion-logs-20230724-15404013710763387800417223.zip](https://github.com/gitbito/bitoai/files/12144862/clion-logs-20230724-15404013710763387800417223.zip)
Note that versions changed:
Bito: 1.1.2
CLion: CLion 2023.2 RC Build #CL-232.8660.139, built on July 20, 2023

**Comment by nisha-bito** [comment]
hi All,

2023.2 release of JetBrains has an issue where all plugin which uses JCEF browser internally are not loading. We are working with JetBrains team and has identified a fix for the same. We shall be releasing a fix within few days.

Alternatively as a workaround, please disable Bito plugin -> save. Enable Bito plugin again. This should load Bito.

Thank you for proving the details.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @peterlee808 , @AlexusYT 

Compatibility issue of Bito with 2023.2 release of JetBrains [all IDE's] is fixed and is available on JetBrains marketplace. Please install the new **Bito version 1.1.3** and let us know if you face any further issues with the same.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @peterlee808  and @AlexusYT ,

Reported issue has been resolved .
This ticket will be closed after few days, please feel free to create a new issue, if you face any further errors.

Thanks,
Nisha
