### ISSUE TITLE
使用vscode remote ssh开发时,如何修改bito的转发端口

### ISSUE THREAD

**Issue by dgyx** [gitbito/bitoai#106]
我们有多人在一台服务器上进行远程开发,似乎有一人设置2511端口后,其他人就没法使用bito了,有什么办法可以解决吗?是否可以通过修改bito使用的端口解决?

**Comment by bitoandy** [comment]
Thanks @dgyx for letting us know about the issue, we are looking into it and will provide an update once we have the fix identified.

**Comment by nisha-bito** [comment]
hi @dgyx ,

Thanks for reporting this issue. We have identified a possible fix for this and the fix shall be available with next Bito release. 

Thanks,
Nisha

**Comment by dgyx** [comment]
Thanks

**Comment by nisha-bito** [comment]
hi @dgyx ,

Reported issue is resolved and is available on JetBrains marketplace. Please install the new **Bito version 1.1.3** and let us know if you face any further issues with the same.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @dgyx ,

Reported issue has been resolved .
This ticket will be closed after few days, please feel free to create a new issue, if you face any further errors.

Thanks,
Nisha
