### ISSUE TITLE
GPT4 or 3?

### ISSUE THREAD

**Issue by smileBeda** [gitbito/bitoai#107]
I am reading some reviews saying it does _not_ run GPT4, see https://marketplace.visualstudio.com/items?itemName=Bito.Bito&ssr=false#review-details

I am firstly not entirely certain how that user comes to the conclusion but secondly, also not entirely sure why you would throw away paid GPT4 API resources - thus, is there a way for us users to see _which_ model actually generated the response?

Thanks for the cool add-on.

**Comment by bitomukesh** [comment]
Hi, thanks for reaching out. We use GPT4 when the context length (prompt + prior conversation in the session) exceeds GPT3.5 limit. Users are generally asking in our chat interface what model Bito uses.  The response is always GPT 3.5. This is the same response you will get if you ask ChatGPT (Pro version) even if you have explicitly selected GPT4 there. 
Right now, Bito is completely free and the cost of GPT4 is 20x of Turbo for input, and 30x for output. So, we use GPT4 only for the larger/complex prompts. In the next couple of weeks, we are launching a paid version that will let users explicitly select the model.

**Comment by smileBeda** [comment]
Thanks!
Yes, clearly asking GPT what version it is using, is silly.

Can I make 2 suggestions while I am here?
1. once you implement a paid version, maybe it is an option to add one's own OpenAI API Keys? Many developers already have api keys, so it would be advantageous to them, if they could use their own keys
2. Allow us to at least see the "source" of your templates, or to duplicate them and then edit on our own. I like the templates, but would like to make some tiny amendments for example to the "write comment" one - the comments are too large, so I would like to adjust the prompt (I Know I can write my own templates, but having insight into the original would help)
