### ISSUE TITLE
Codebase context

### ISSUE THREAD

**Issue by Dr-42** [gitbito/bitoai#108]
Is there any way for the AI to index the entire code in the working directory and analyze that and answer accordingly? Something like ChatGPT-EasyCode dows with code base indexing?

**Comment by Dr-42** [comment]
I see. Thank you. Looking forward to it.

**Comment by monicfenga** [comment]
I had sent her ten messages letting her know what functions I had on my side (each message included a function) and wrote code that use those functions

**Comment by bitomukesh** [comment]
that's great to hear @monicfenga

**Comment by nisha-bito** [comment]
hi @Dr-42 ,

Bito has launched "AI that Understands Your Code" with Bito version 1.1.4. 
This is available with a paid subscription. 

Thanks,
Nisha

**Comment by amargoel98** [comment]
@Dr-42 , We will launch it for free members in September too, for repos up to 10MB in size.
