### ISSUE TITLE
It Stopped Working

### ISSUE THREAD

**Issue by JohannesBitcube** [gitbito/bitoai#109]
It stopped working. keeps on saying "Signing me in"  and loading no stop

**Comment by nisha-bito** [comment]
hi @JohannesBitcube ,

Can you please let us know few more details to analyze further:
1. OS 
2. Bito version 
3. IDE and its version 
4. console logs [if you can share by opening developer tools] 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @JohannesBitcube ,

Please provided required information to further analyze the issue. 
Please note, this ticket will be auto closed in few days if not response is provided, please feel free to create a new ticket in case the problem still exists.

Thanks,
Nisha

**Comment by aaronms1** [comment]
Bito was working perfectly, until I updated Intellij to 2023.2. 
Now the window that normally has options, work spaces..etc... is just blank

OS= Linux parrot 6.1.0-1parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Parrot 6.1.15-1parrot1 (2023-04-25) x86_64 GNU/Linux
any debian based packages work on Parrot(as i said, it was working perfect)

Bito version 1.1.2

There are no logs at all returned

one thing that was different after I updated Intellij, while trying to utilize Bito, it made my OS "request password to unlock my GPG keys"  info box pop up, which is normal after an update(for intellij), but after i entered my key passwords, Bito stopped working..

**Comment by nisha-bito** [comment]
hi @aaronms1 ,

There is an issue with 2023.2 JetBrains release which has made Bito incompatible. We are working with JetBrains team and has identified a possible fix.
The fix shall be releases with Bito next update.

Thanks,
Nisha

**Comment by aaronms1** [comment]
thank you for your speedy response!

**Comment by nisha-bito** [comment]
hi @aaronms1 and @JohannesBitcube ,

Compatibility issue of Bito with 2023.2 release of JetBrains [all IDE's] is fixed and is available on JetBrains marketplace. Please install the new **Bito version 1.1.3** and let us know if you face any further issues with the same.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @aaronms1  and @JohannesBitcube ,

Reported issue has been resolved . 
This ticket will be closed after few days, please feel free to create a new issue, if you face any further errors. 

Thanks,
Nisha
