### ISSUE TITLE
Whitespace not properly formatted

### ISSUE THREAD

**Issue by rauwebieten** [gitbito/bitoai#110]
The bot generates whitespace correctly, but the jetbrains plugin renders the white space form the output incorrectly.

Given code:

```php
<?php

$a = ''; 

$b = '';

$c = '';

class Appel
{
    
}
```

and the command:

```
keep whitespace
```

Gives me following result:

![Screenshot 2023-07-12 104413](https://github.com/gitbito/bitoai/assets/11740475/3c6716cc-a09f-478f-ab86-b8a4c48dd15e)

All empty lines are gone.
The class code has a space prefix on each line.

This happens on every command.
Code is never property formatted, which makes the plugin hard to use

Plugin version 1.1.2

**Comment by nisha-bito** [comment]
hi @rauwebieten,

Thank you for reporting the issue. We will analyze the issue at our end.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @rauwebieten ,

We have identified a possible fix and the fix shall be available in the next Bito release. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @rauwebieten ,

Reported issue is resolved and is available on JetBrains marketplace. Please install the new **Bito version 1.1.3** and let us know if you face any further issues with the same.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @rauwebieten ,

Reported issue has been resolved . 
This ticket will be closed after few days, please feel free to create a new issue, if you face any further errors. 

Thanks,
Nisha
