### ISSUE TITLE
FEATURE REQUEST: Web Browsing

### ISSUE THREAD

**Issue by aemonqe** [gitbito/bitoai#111]
Is the implemention of live web access planned?
Bito can't help on anything newer than october 2021.

**Comment by monicfenga** [comment]
like "try bito with no install(that only can try 5 rounds of q&a)" link in the bito website

**Comment by nisha-bito** [comment]
hi @aemonqe and @monicfenga ,

You can login via https://alpha.bito.ai/bitoai/ and use Bito via Web Browser. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @aemonqe  and @monicfenga ,

Please note, this ticket will be auto closed in few days, please feel free to create a new ticket in case the problem still exists.

Thanks,
Nisha

**Comment by aemonqe** [comment]
@monicfenga I didn't mean our web browser.

I ment internet browsing functionality like phind.com has - so Bito can analyze websites and more present data too.
