### ISSUE TITLE
after open ipynb file "cmd+c" error when copy from BITO

### ISSUE THREAD

**Issue by Kurt-Shiwz** [gitbito/bitoai#112]
-   VS Code version: 1.80.1 (Universal)
-   macOS 13.4.1
-   BITO : v1.1.2

when open .ipynb and then open 'Bito' , copy chatGPT's answer, but copy a cell (which cell mouse focus on).
But when open other file(such as .py/.sh/.log) don't has this problem.

![image](https://github.com/microsoft/vscode-jupyter/assets/7554917/839f47b7-3707-4672-b470-c4588fad91f4)

**Comment by nisha-bito** [comment]
hi @Kurt-Shiwz ,

Please try 
1. Right click and click on copy after selecting the text
2. Or select a text ad do command+C.

Let us know if any of the above works for you ? 

Thank,
Nisha

**Comment by Kurt-Shiwz** [comment]
> hi @Kurt-Shiwz ,
> 
> Please try
> 
> 1. Right click and click on copy after selecting the text
> 2. Or select a text ad do command+C.
> 
> Let us know if any of the above works for you ?
> 
> Thank, Nisha

1. Right click and click on copy after selecting the text
The same result

2. Or select a text ad do command+C.
The same result

It just happens on `.ipynb` file.

**Comment by nisha-bito** [comment]
hi @Kurt-Shiwz ,

Bito is not fully supported in Jupyter notebook for Copy/paste/Insert and diff. However we have this in our pipeline. 
thanks for reporting this. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Kurt-Shiwz ,

This ticket will be closed now, feel free to create new ticket for any further issues. 

Thanks,
Nisha
