### ISSUE TITLE
Can't log in on IntelliJ plugin with email that contains special character "-"

### ISSUE THREAD

**Issue by jslevacque** [gitbito/bitoai#113]
I installed recently the plugin ChatGPT GPT-4 BITO on my IntelliJ IDE. I validated my account on the website workspace. Everything is perfect until I tried to use the plugin on my IDE.

It requires to log in with an email, but mine contains a special character "-" which is not allowed from validation form. Probably the regex rule does not allow it.

Here is some screenshots:
without the "-":
![image](https://github.com/gitbito/bitoai/assets/41906971/42a78623-6c8b-42f4-94cc-7ba4a4ccaaf7)

with the "-", it does not allow to connect:
![image](https://github.com/gitbito/bitoai/assets/41906971/ca5b034b-35d9-4290-b9c6-e14f4a8ff981)

**Comment by nisha-bito** [comment]
hi @jslevacque ,

We will look into the issue. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @jslevacque ,

The fix shall be available with next Bito release which will be available in next few days.
Thanks for reporting the issue.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @jslevacque ,

Reported issues is resolved and is available on JetBrains marketplace. Please install the new **Bito version 1.1.3** and let us know if you face any further issues with the same.

Thanks,
Nisha

**Comment by jslevacque** [comment]
Hi @nisha-bito,

Thank you for the update, it seems I can log in now.

Jean-Seb
