### ISSUE TITLE
exception in login from vscode extension

### ISSUE THREAD

**Issue by abu-sufyan1** [gitbito/bitoai#114]
VS Code Version 1.80.1 (user setup)
Operating System: Windows 11 Home

When I login to Bito from Visual Studio Code, it gives exception message.
![image](https://github.com/gitbito/bitoai/assets/24729451/d4dca4c4-0579-4351-a992-de1a3eef60c1)

**Comment by weiqiyue** [comment]
The same goes for jetbrains

**Comment by Halcyon666** [comment]
the same with me,.
![image](https://github.com/gitbito/bitoai/assets/40227502/06a93743-6813-48da-a36e-8ef52055757e)
bito version: 1.12
IDEA Version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
System:Windows 10.0 Enterprise version

![image](https://github.com/gitbito/bitoai/assets/40227502/ce5182ed-f282-49dc-bb28-7d30bcde4f34)

best regard!

**Comment by bitoandy** [comment]
We are looking into this one our end and have found an issue which we are working on fixing. Will keep all of you posted once we have fixed the issue.

**Comment by bitoandy** [comment]
Hi All,

We have fixed the service causing the issue with login. Please try to login again and let us know if you see any issues.

**Comment by Halcyon666** [comment]
This worked, my account auto login once I open IntelliJ IDEA.
thanks a lot.

**Comment by abu-sufyan1** [comment]
@bitoandy - Thanks for the fix. I guess - It's working for all of you now.

**Comment by abu-sufyan1** [comment]
We are good to close the issue. Thanks again team for quick action.
