### ISSUE TITLE
IDEA2023.2版本安装后闪退

### ISSUE THREAD

**Issue by wzlstudy** [gitbito/bitoai#116]
在IntelliJ IDEA 2023.2 和 WebStorm 2023.2 上安装最新版本后，打开时软件闪退

**Comment by bitoandy** [comment]
Hi @wzlstudy ,

Thanks for reporting this issue, we are looking into this. If possible do share a  short video of the issue, that will help us to get to the issue quicker.

**Comment by bitoandy** [comment]
Hi @wzlstudy ,

We are still working on this issue. One alternative to get Bito working with 2023.2 is to do following:
Go to settings and then plugins. Under installed plugins select Bito and then disable it:
<img width="1094" alt="Screenshot 2023-07-27 at 3 46 44 PM" src="https://github.com/gitbito/bitoai/assets/125080245/8fd2f349-814e-4c9b-9352-919c2e3fe9bc">
Once the plugin is disable, enable it again:
<img width="1094" alt="Screenshot 2023-07-27 at 3 48 35 PM" src="https://github.com/gitbito/bitoai/assets/125080245/8982ac61-aa45-4a6d-8b7d-9412401a183c">

Once the Bito plugin is enabled again it will start working:
<img width="1489" alt="Screenshot 2023-07-27 at 3 57 51 PM" src="https://github.com/gitbito/bitoai/assets/125080245/5ec384df-2139-48bb-8667-68f1b8db32f5">

**Comment by bitoandy** [comment]
Hi @wzlstudy ,

Let us know if the workaround works for you.

**Comment by wzlstudy** [comment]
没有效果，IDEA任然闪退

**Comment by nisha-bito** [comment]
hi @wzlstudy ,

Please ensure that you are disabling the Bito plugin -> apply and save. Once the Bito logo/plugin disappear from the right panel, then go to plugins -> enable the Bito again. 

Let us know in case this is not working. 

Thanks
nisha

**Comment by wzlstudy** [comment]
按照你说的操作，先disable再enable后，点击项目打开时IDEA直接闪退，我确定，这么操作是无效的
[java_error_in_idea_33914.log](https://github.com/gitbito/bitoai/files/12205350/java_error_in_idea_33914.log)
这个是IDEA闪退后产生的错误日志，希望能帮助到你

**Comment by bitoandy** [comment]
Thanks @wzlstudy for the logs, we have the fix for this in the works which will be available in the next update for Bito.

**Comment by silverflute** [comment]
WebStorm 2023.2

**Comment by bitoandy** [comment]
Hi @silverflute , we have the fix for this in the works which will be available in the next update for Bito, which is expected soon.

**Comment by nisha-bito** [comment]
hi All,

2023.2 release of JetBrains has an issue where all plugin which uses JCEF browser internally are not loading. We are working with JetBrains team and has identified a fix for the same. We shall be releasing a fix within few days.

Alternatively as a workaround, please disable Bito plugin -> save. Enable Bito plugin again. This should load Bito. 

Thank you for proving the details.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @All,

Compatibility issue of Bito with 2023.2 release of JetBrains [all IDE's] is fixed and is available on JetBrains marketplace. Please install the new **Bito version 1.1.3** and let us know if you face any further issues with the same.

Thanks,
Nisha
