### ISSUE TITLE
Bito AI not working on PhpStorm Build 2023.2 RC

### ISSUE THREAD

**Issue by mm-novelt** [gitbito/bitoai#117]
Hello,

The JetBrains BitoAi plugin doesn't work on PhpStorm Build #PS-232.8660.153, built on July 21, 2023
The plugin windows still empty.

![image](https://github.com/gitbito/bitoai/assets/108662851/91a2c155-f225-4ca4-9066-c122436994f2)

**Comment by bitoandy** [comment]
Hi @mm-novelt ,

We are looking into this issue and will keep you posted on the updates.

**Comment by bitoandy** [comment]
Hi @mm-novelt ,

Let us know if the workaround mentioned above works for you.

**Comment by mm-novelt** [comment]
Hi @bitoandy, It's work now with your workaround. Thanks
