### ISSUE TITLE
最新版本不能用了，窗口是空白的

### ISSUE THREAD

**Issue by 1592363624** [gitbito/bitoai#118]
内部版本号 #IU-232.8660.185，2023年7月26日 构建

**Comment by deepinsideDrury** [comment]
2023.2直接闪退

**Comment by 1592363624** [comment]
> 2023.2直接闪退

我这个版本就是2023.2的 但是没闪退

**Comment by bitoandy** [comment]
Hi @1592363624 ,

We are looking into this issue. One alternative to get Bito working with 2023.2 is to do following:
Go to settings and then plugins. Under installed plugins select Bito and then disable it:
<img width="1094" alt="Screenshot 2023-07-27 at 3 46 44 PM" src="https://github.com/gitbito/bitoai/assets/125080245/8fd2f349-814e-4c9b-9352-919c2e3fe9bc">
Once the plugin is disable, enable it again:
<img width="1094" alt="Screenshot 2023-07-27 at 3 48 35 PM" src="https://github.com/gitbito/bitoai/assets/125080245/8982ac61-aa45-4a6d-8b7d-9412401a183c">

Once the Bito plugin is enabled again it will start working:
<img width="1489" alt="Screenshot 2023-07-27 at 3 57 51 PM" src="https://github.com/gitbito/bitoai/assets/125080245/5ec384df-2139-48bb-8667-68f1b8db32f5">

**Comment by bitoandy** [comment]
@1592363624 , let us know if the above workaround/ alternative works for you.

**Comment by 1592363624** [comment]
> 嗨，
> 
> 我们正在调查这个问题。让Bito使用2023.2的一种替代方法是执行以下操作：转到设置，然后转到插件。在已安装的插件下，选择 Bito，然后禁用它： 禁用插件后，再次启用它： [<img alt="Screenshot 2023-07-27 at 3 46 44 PM" width="1094" src="https://user-images.githubusercontent.com/125080245/256507041-8fd2f349-814e-4c9b-9352-919c2e3fe9bc.png">](javascript:void(0)) [<img alt="Screenshot 2023-07-27 at 3 48 35 PM" width="1094" src="https://user-images.githubusercontent.com/125080245/256507141-8982ac61-aa45-4a6d-8b7d-9412401a183c.png">](javascript:void(0))
> 
> 再次启用Bito插件后，它将开始工作： [<img alt="Screenshot 2023-07-27 at 3 57 51 PM" width="1489" src="https://user-images.githubusercontent.com/125080245/256508822-5ec384df-2139-48bb-8667-68f1b8db32f5.png">](javascript:void(0))

good    thanks

**Comment by nisha-bito** [comment]
Thanks for confirming. 
The fix is identified and shall be available in few days with next Bito update
