### ISSUE TITLE
Crashes JetBrains Rider 2023.2 RC 1

### ISSUE THREAD

**Issue by dps999** [gitbito/bitoai#119]
Hi,
it crashes whole editor when I open it in JetBrains Rider 2023.2 RC 1

**Comment by bitoandy** [comment]
Thanks @dps999 for reporting the issue, we are looking into it and will keep you posted on the updates.

**Comment by nisha-bito** [comment]
hi @dps999 ,

We are still working on this issue. One workaround, alternative to get Bito working with 2023.2 is to do following:
Go to settings and then plugins. Under installed plugins select Bito and then disable it:
<img width="1094" alt="Screenshot 2023-07-27 at 3 46 44 PM" src="https://github.com/gitbito/bitoai/assets/125080245/8fd2f349-814e-4c9b-9352-919c2e3fe9bc">
Once the plugin is disable, enable it again:
<img width="1094" alt="Screenshot 2023-07-27 at 3 48 35 PM" src="https://github.com/gitbito/bitoai/assets/125080245/8982ac61-aa45-4a6d-8b7d-9412401a183c">

Once the Bito plugin is enabled again it will start working:
<img width="1489" alt="Screenshot 2023-07-27 at 3 57 51 PM" src="https://github.com/gitbito/bitoai/assets/125080245/5ec384df-2139-48bb-8667-68f1b8db32f5">


Thanks,
Nisha

**Comment by bitoandy** [comment]
Hi @dps999 ,

Let us know if the above worked for you. We are working with JetBrains and have the fix for this in the works which will be available in the next update.

**Comment by nisha-bito** [comment]
hi @dps999 ,

2023.2 release of JetBrains has an issue where all plugin which uses JCEF browser internally are not loading. We are working with JetBrains team and has identified a fix for the same. We shall be releasing a fix within few days.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @dps999 ,

Reported issue has been resolved . 
This ticket will be closed after few days, please feel free to create a new issue, if you face any further errors. 

Thanks,
Nisha
