### ISSUE TITLE
Intellij idea is 2023.02 not working....[edited]

### ISSUE THREAD

**Issue by SpaceMichael** [gitbito/bitoai#120]
message as below.....
=================
Unknown Host
Description: Unable to locate the server named "ideapp" --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.

**Comment by nisha-bito** [comment]
hi @SpaceMichael ,

Please provide below information for us to analyze the issue at details 
1. OS 
2. IntelliJ version [2029.02 mut be a typo] 
3. Are you using proxy ? 
4. Please share Help -> Find logs in Explorer ->idea.log 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @SpaceMichael ,

2023.2 release of JetBrains has an issue where all plugin which uses JCEF browser internally are not loading. We are working with JetBrains team and has identified a fix for the same. We shall be releasing a fix within few days.

Thank you for proving the details. 

Thanks,
Nisha

**Comment by SpaceMichael** [comment]
Hi @nisha-bito ,

It was work now. Thank you!  ^^

**Comment by sfcecy7i** [comment]
@nisha-bito 
Does Android studio Giraffe have the same issue?

**Comment by nisha-bito** [comment]
@sfcecy7i 
Yes.
