### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by Julius-Nova-Chrono** [gitbito/bitoai#122]
Type: <b>Bug</b>

Cuando intento usar la extencion de Bito y otras mas me aparece esto Error al cargar la vista web: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.
Tambien con otras ectensiones que tengo

Extension version: 1.1.2
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.88GB (0.30GB free)|
|Process Argv|--crash-reporter-id 62f113f7-ee80-479d-9cca-2a2fa94a5491|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by Julius-Nova-Chrono** [comment]
Que hago

**Comment by bitoandy** [comment]
Hi @Julius-Nova-Chrono ,

We are looking into the issue and will provide an update soon.

**Comment by nisha-bito** [comment]
hi @Julius-Nova-Chrono ,

Sometime the VS code extension when not installed correctly, we get this error. Please try below workaround to resolve it - 
1. Restart VS code 
2. Uninstall and Install Bito extension again 
3. ctrl+Shift+P -> type Developer : Reload windows and then restart VS code 

Let us know if any of the above works for you.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Julius-Nova-Chrono ,

Gentle reminder. 
Did above steps helps you access Bito properly? 

Thanks,
Nish

**Comment by nisha-bito** [comment]
hi @Julius-Nova-Chrono 

Did above steps helps you access Bito properly? 
In absence of the response, this ticket will be closed now, please feel free to create a new issue, if you face any further errors.

Thanks,
Nisha
