### ISSUE TITLE
bito requesting different port after update on vscode

### ISSUE THREAD

**Issue by RebelSoftware** [gitbito/bitoai#124]
I am running bito in vscode in a remote session, updated two days ago, so its the latest version.

When I start vscode this message pops up 
![image](https://github.com/gitbito/bitoai/assets/40537539/cd80ac9b-4f2b-459f-973e-9729348aee88)

This is a different port to 2511and even though port 2511 is statically forwarded bito wont recognise my account until the new port is opened.

if I restart the environment a different port is asked for
![image](https://github.com/gitbito/bitoai/assets/40537539/4fa3e086-0729-4848-9e62-299e8d4e869e)

I cannot find an entry for bito in the settings and there is no mention of port numbers in the documentation.

Can I configure bito to use the same port each time [2511] rather than selecting a random port. it makes it very tiresome to have to reconfigure it each time I load vscode.

**Comment by nisha-bito** [comment]
hi @RebelSoftware ,

As of now, every time VS code restarts or you change your project, you need to enter the Port number to use VS code in SSH mode. 
Port number can be found in the notification which is generated via Bito. 

We are looking for more generic way of solving this. 

Thanks,
Nisha

**Comment by RebelSoftware** [comment]
Thanks.

**Comment by huawuya** [comment]
I have the same issue, I am the only one using the remote machine, and hope to use the same port every time

**Comment by nisha-bito** [comment]
Hi @huawuya  and @RebelSoftware ,

Hope you are not facing any further issue. We have added the request in our roadmap. 
We will be closing this ticket, please feel free to create new ticket if the issue still persists.

Thanks,
Nisha
