### ISSUE TITLE
[Suggestion] make the `Bito` always focused on my project

### ISSUE THREAD

**Issue by BachiMjavanadze** [gitbito/bitoai#130]
At the moment, in order for the `Bito` to understand that I'm asking him abote my project (not a general question)  you need to use special terms: `in my project` or `in my repo`.

Since in most cases my question refers to my project and not general question, I think you should revert `Bito's` behavior. 

I think these special terms (`in my project` or `in my repo`) should be made default so that I don't have to write them again and agein. If I want to ask general question that's when I need to clarify with special terms: `not in my project` or `general question`.

Of course, I can ask a general question, forgetting that `Bito` is focused on my project and to remind me the context, let `Bito's`answer begin like this:  `in your project` or `in your repo`.

**Comment by zvalcav** [comment]
Rather than making it default, what about check box, which you can check if you need longer conversation about your code? Making one or the other behavior default is too limiting. But letting Bito know you now want to talk about your code by marking the check box seems OK to me.

**Comment by BachiMjavanadze** [comment]
> Rather than making it default, what about check box, which you can check if you need longer conversation about your code?

I prefer my suggestion but your suggestion definitely is better than existing behavior.

**Comment by nisha-bito** [comment]
hi @BachiMjavanadze / @zvalcav  - 

We have made some improvement in identifying the Local code relates queries. It will ask you if the question you are asking in related to local code or not, when you dont specify the "my code" or "my project". 

Refer to documentation for more details - https://docs.bito.ai/feature-guides/ai-that-understands-your-code

I hope this will help you in using Bito. 
Feel free to re-open the ticket in case you want to report nay further bugs.

Thanks,
Nisha
