### ISSUE TITLE
bito crashing IntelliJ Ultimate

### ISSUE THREAD

**Issue by nmschoolcraft** [gitbito/bitoai#131]
running IntelliJ Ultimate on Mac, and when app tries to load with Bito installed, it hangs, when i remove, IntelliJ loads. please adivse.

**Comment by j4m355** [comment]
Same issue here since taking the update from 1.1.3 to 1.1.4.

Not just confined to IntelliJ Ultimate. Having the same issue in DataSpell 2023.2.

Is there a downgrade pathway?

**Comment by bitoandy** [comment]
To downgrade, you can download the previous version from: https://plugins.jetbrains.com/plugin/18289-chatgpt--bito-ai-code-assistant/versions

After downloading, uninstall the current version and then install plugin from disk using the version downloaded.

We are looking into this issue and we will keep you posted on the fix and updates related to the same.

**Comment by bitoandy** [comment]
@nmschoolcraft , @j4m355 ,

Let us know if you are still seeing the issue with 1.1.6 build available on marketplace?

**Comment by j4m355** [comment]
Working for me now on 1.1.6.  Thank you!

**Comment by bitoandy** [comment]
Thanks @j4m355  for confirming, closing this issue.
