### ISSUE TITLE
ChatGPT GPT-4 - Bito AI Code Assistant Crashed with Android Studio Giraffe 2022.3.1 Patch 1

### ISSUE THREAD

**Issue by adhamalaa111** [gitbito/bitoai#133]
![Screenshot 2023-09-04 160735](https://github.com/gitbito/bitoai/assets/49401600/acf566cd-397b-4eba-8a22-8d5608fb52e2)

**Comment by bitoandy** [comment]
Hi @adhamalaa111 ,

We are looking into this and we will keep you posted on the updates.

**Comment by nisha-bito** [comment]
hi @adhamalaa111 ,

Can you please confirm if jcef Brower is enable in your android studio ? JCEF browser needs to eb enabled for Bito plugin to load. 

please refer to this document for more details - https://docs.bito.ai/support-and-questions/troubleshooting

Thanks,
Nisha

**Comment by adhamalaa111** [comment]
hi @nisha-bito Of course JCEF it wasn't enabled and after enabled Bito Now is Working 😊
Thanks,
![Screenshot 2023-09-05 171225](https://github.com/gitbito/bitoai/assets/49401600/83bd91e8-31ad-41f2-9110-b3fa3124cd51)

**Comment by bitoandy** [comment]
Awesome, thanks for confirming @adhamalaa111 , closing this issue
