### ISSUE TITLE
I am using bito version 1.1.6, there is no new template button, what is the reason?

### ISSUE THREAD

**Issue by leexuGit** [gitbito/bitoai#135]
I am using bito version 1.1.6, there is no new template button, what is the reason? I use bito through the nginx agent.

**Comment by bitoandy** [comment]
Hi @leexuGit ,

We currently support up to 4 templates. So once you have 4 templates created you will not see "New Template" button.
More information at: https://docs.bito.ai/feature-guides/custom-prompt-templates

Let us know if you are not seeing the "New Template" button when you have not already created 4 templates. 

In case you need more templates supported, let us know and we will based on the feedback add it to our product roadmap.
