### ISSUE TITLE
In VS Code, some keyboard shortcuts not working

### ISSUE THREAD

**Issue by sika** [gitbito/bitoai#138]
I can not get keyboard shortcuts related to the Bito window to work (others from inside the IDE editor, like Insert Code Into Bito, work). In particular I have been trying to use the shortcut for Insert Changes. The exception for me is Regenerate (ctrl+m) which works. 

![iScreen Shoter - Code - 230911183153](https://github.com/gitbito/bitoai/assets/10941885/7e9c0c17-ac66-4490-b3c9-dd4295929f06)

1. VS code version: Version: 1.82.0 (Universal)
2. OS: Ventura 13.5.2 on Mac
3. Bito Version: v1.1.7

**Comment by nisha-bito** [comment]
hi @sika ,

Thanks for reporting this.
We will work on the fix and hopeful to release the fix with next Bito update.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @sika ,

Please download and install latest version 1.1.8, which the the fix for the above reported issue. 
Let us known if you face any further issue.

Thanks,
Nisha

**Comment by sika** [comment]
hi @nisha-bito,

Thank you for your reply. I have updated to 1.18 but unfortunately I can't get it to work.

CTRL+i does not work. When I search for 'bito' in keyboard shortcuts I can't find anything regarding 'Insert Changes'. Below is what I get when searching for 'bito' (I have already tried the two called 'Insert Code Into Bito' but they only copy _to_). Am I doing something wrong or need to search for anything else?

![iScreen Shoter - Code - 230929181139](https://github.com/gitbito/bitoai/assets/10941885/03a4c3b8-147b-4279-b9e8-335e626825b7)
![iScreen Shoter - 20230929181302652](https://github.com/gitbito/bitoai/assets/10941885/b4fe1dcd-9f9e-47ff-8b30-9a3e51c3fcd7)
![iScreen Shoter - Code - 230929181333](https://github.com/gitbito/bitoai/assets/10941885/ecb5e792-ba21-4eb3-8a9a-8f1364c2c47f)

**Comment by nisha-bito** [comment]
hi @sika ,

Can you please upgrade to Bito 1.2.4 and validate of the fix is working for you ?

Thanks,
Nisha

**Comment by sika** [comment]
Hello @nisha-bito,

I'm sorry but no, it does not seem to work.

**Comment by nisha-bito** [comment]
hi @sika ,

We will validate further on our side. 

Thanks,
nisha

**Comment by sika** [comment]
Hello @nisha-bito,

I recorded and uploaded (available for 7 days) a video which I hope shows what I'm trying to do (replicating you): https://we.tl/t-niOfz7gjAO

I have also updated to version 1.2.5

**Comment by nisha-bito** [comment]
hi @sika ,

I see that your whole screen is selected and not the question/answer section. Please use keyboard up or down arrow or select the exact chat then it will work as expected.
Screenshot where only the chat session is selected [Check the blue border] 
![image](https://github.com/gitbito/bitoai/assets/123052606/312443b1-cd1f-49b8-9f06-93e72f7f0f8a)

Screenshot when the entire session is selected
![image](https://github.com/gitbito/bitoai/assets/123052606/dcb8838a-61f8-4f32-9427-94ab1a6f0361)

Thanks,
nisha

**Comment by sika** [comment]
hi @nisha-bito,

You´re right, that works - thank you!

**Comment by nisha-bito** [comment]
thanks for confirming.
