### ISSUE TITLE
How do I change the font and size in JetBrains IDE?

### ISSUE THREAD

**Issue by sthornington** [gitbito/bitoai#140]
I have a custom font and size set for both UI and editor elements, but the BITO plugin seems to be using neither of those settings and I cannot adjust the font at all.  Please help, thanks!

**Comment by nisha-bito** [comment]
hi @sthornington ,

Please use this setting to increase the font. You will have to restart IDE once so the font size of Bito can be reflected after the setting is modified. 

![image](https://github.com/gitbito/bitoai/assets/123052606/51aa5365-aeda-4a81-ad4c-3a9cec419e3c)

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @sthornington ,

I hope above suggestion has resolved your problem.

This issue will be closed now. Please feel free to re-open the issue in case you still face the issue.

Thanks,
nisha
