### ISSUE TITLE
Wrong language in Cli and  Chrome Extention

### ISSUE THREAD

**Issue by slavonnet** [gitbito/bitoai#141]
In settings  choice "Russian" but in cmd  and in web extention default is eng. If i ask to change to run in text message this will help got current session on;u

Also russia files loaded in console from `cat`  does remove all rus simbols in request.  I think its because condole in 866 (cp1251 codepage)? but all files utf8

**Comment by slavonnet** [comment]
Licenses to russia don't sell OpenAI. Lets fix all stupid errors and go to us wuth service!

**Comment by nisha-bito** [comment]
hi @slavonnet ,

Bito CLI now has support for language. The Language setting needs to be updated in alpha.bito.ai. Please do let us know if this helps you. 

Thanks,
Nisha
