### ISSUE TITLE
Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute

### ISSUE THREAD

**Issue by DakJaniels** [gitbito/bitoai#142]
![bito_cookie](https://github.com/gitbito/bitoai/assets/107732615/963f4fb1-d2f5-44a6-a2d6-8e4c65a1f200)
Visual Studio Code:
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by bitoandy** [comment]
Thanks @DakJaniels, we will add the fix for this and update.

**Comment by nisha-bito** [comment]
Fix is added for the same.
