### ISSUE TITLE
Android Studio and java 17 doesn't work

### ISSUE THREAD

**Issue by Eiffelyk** [gitbito/bitoai#143]
https://github.com/gitbito/bitoai/issues/44
The solution given by @nisha-bito  was to change the BootRuntime to JCEE, but after the change, Android Studio became super slow, resulting in no work, and I hope to support Android Studio as soon as possible

![](https://user-images.githubusercontent.com/123052606/240222427-e8231185-f6d9-406d-b5b8-8c7bfa272099.png)

**Comment by ynagarjuna2012** [comment]
I second this. Boot up itself took good amount of time. Have Intel Chip on my Mac.

**Comment by nisha-bito** [comment]
hi @ynagarjuna2012 , @Eiffelyk ,

We will be closing the ticket in some days. Please feel free to re-open ticket or a create new ticket in case you have further issues.
Thank you for reporting the issue.

Thanks,
Nisha
