### ISSUE TITLE
Asking me to login every time i open my IDE

### ISSUE THREAD

**Issue by apioff** [gitbito/bitoai#145]
Why do i have to login every time i open my Jet-brain IDE ?

![image](https://github.com/gitbito/bitoai/assets/17923943/6472b5f0-7206-48b2-adb5-4b67682fa01f)

**Comment by nisha-bito** [comment]
hi @apioff ,

Can you please provide below information to help us debug the issue -
1. Operating System 
2. Bito version 
3. Which JetBrains IDE and its version ? 
4. Email you are using to login into Bito ? 
5. Can you please try to delete the .bito from /users/home/.bito [C:\Users\user\.bito] and restart IDE 
6. If this doesn't help, can you please share the idea.log [Action -> Open log in Explorer] 
7. Have you login and selected a workspace in the IDE successfully once? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @apioff ,

Gentle reminder to send the required information for us to further analyze the issue.
Please note, the ticket will automatically be closed in next 7 days. please help us with more information to analyze this further. 

Thanks,
Nisha
