### ISSUE TITLE
VS Code error when using any default prompts with a temp file 

### ISSUE THREAD

**Issue by DakJaniels** [gitbito/bitoai#147]
![image](https://github.com/gitbito/bitoai/assets/107732615/afc3c9b4-edfa-4622-afba-db1b74655118)

Version: 1.82.3 (user setup)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T10:51:22.294Z
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

![image](https://github.com/gitbito/bitoai/assets/107732615/8ac3ecaf-10bf-49bb-ae88-b49605121218)

How to reproduce:
Create a new file, do not save it
Add any type of code to the temp file
then run a performance check, etc. on the code and you will get a error
I believe this is because "Diff view" can't be created on a temporary file because it itself is a temporary file?

**Comment by bitoandy** [comment]
Thanks @DakJaniels for identifying the issue and providing scenario for repeating it. We are working on this and will provide an update on this.

**Comment by nisha-bito** [comment]
hi @DakJaniels ,

Bito latest version 1.1.9 has fix for this. Please install the new Bito 1.1.9 and let us know if this fix your problem.

Thanks,
Nisha

**Comment by DakJaniels** [comment]
It looks like it is working correctly now, Thank you.
