### ISSUE TITLE
when generating code, the "code dif" view shows always the exact same code, So have to paste it over manually 

### ISSUE THREAD

**Issue by reece00** [gitbito/bitoai#148]
![image](https://github.com/gitbito/bitoai/assets/37351410/72580db8-a4f5-4dfd-88c5-67f561401aba)

**Comment by bitoandy** [comment]
Hi @reece00 ,

Thanks for raising this issue. We will keep you posted on updates.

**Comment by nisha-bito** [comment]
hi @reece00 ,

Bito latest version 1.1.9 has fix for this. Please install the new Bito 1.1.9 and let us know if this fix your problem.

Thanks,
Nisha

**Comment by reece00** [comment]
The problem has not appeared again, it should be solved
