### ISSUE TITLE
关于查询xml文件符号转义的问题

### ISSUE THREAD

**Issue by zx798928321** [gitbito/bitoai#153]
当我查询xml文件符号转义相关的问题时，它返回的回答给我的是转义后的结果，是不是回答里面做了一层处理？
![c99f4838a301f3f54e1c4160c62d529](https://github.com/gitbito/bitoai/assets/32585742/8f5f8f85-7511-43c6-acb0-5eb1bddeb539)

**Comment by nisha-bito** [comment]
hi @zx798928321 ,

Can you help us with some example of prompts in text format [not screenshot]  to better analyze this? 

Thanks,
Nisha

**Comment by zx798928321** [comment]
> hi @zx798928321 ,
> 
> Can you help us with some example of prompts in text format [not screenshot] to better analyze this?
> 
> Thanks, Nisha

ok.

Question 
springboot的Mapper.xml文件中的<符号需要怎么表示?
Answer :
在Spring Boot的Mapper.xml文件中，如果需要使用小于号“<”，则需要使用实体字符“<”来代替。这是因为小于号是XML中的保留字符，需要进行转义才能在XML文件中正常使用。同样，大于号“>”也需要使用实体字符“>”来代替。(This is what I copied by copying shortcut keys)
在Spring Boot的Mapper.xml文件中，如果需要使用小于号“<”，则需要使用实体字符“&lt;”来代替。这是因为小于号是XML中的保留字符，需要进行转义才能在XML文件中正常使用。同样，大于号“>”也需要使用实体字符“&gt;”来代替。(This is what I copied using your copy button)

Question 
springboot的Mapper.xml文件中的“<”小于的计算符号转义怎么表示？
Answer :
在Spring Boot的Mapper.xml文件中，小于号“<”需要使用实体字符“<”来代替。这是因为小于号是XML中的保留字符，需要进行转义才能在XML文件中正常使用。同样，大于号“>”也需要使用实体字符“>”来代替。(This is what I copied by copying shortcut keys)
在Spring Boot的Mapper.xml文件中，小于号“<”需要使用实体字符“&lt;”来代替。这是因为小于号是XML中的保留字符，需要进行转义才能在XML文件中正常使用。同样，大于号“>”也需要使用实体字符“&gt;”来代替。(This is what I copied using your copy button)

and I am using an idea plugin.

**Comment by nisha-bito** [comment]
thanks @zx798928321 ,

We are looking into the issue.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @zx798928321 ,

This issue has been resolved, can you please upgrade to latest version of Bito 1.2.4 and validate the fix.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @zx798928321 ,

Please confirm if this is working for you now ? 
Please note this issue will be automatically close in next 7 days if no further update is provided. you are free to open a new ticket in case needed.

Thanks
Nisha
