### ISSUE TITLE
Indexing the private repo (Gitlab, Github)

### ISSUE THREAD

**Issue by JackOman69** [gitbito/bitoai#159]
Hello! Thank you for your amazing job and project!
I'd like to ask you, what should I do to not indexing the git repo in my local project (because it's the private repo on self-hosted Gitlab) and make bito focusing on local files in directory?

**Comment by bitoandy** [comment]
Hi @JackOman69 ,
You can use .bitoignore file to add rules to ignore files that you do not want to index.
For more information checkout: https://docs.bito.ai/feature-guides/ai-that-understands-your-code/managing-index-size#what-is-.bitoignore-and-how-to-use-it
Also note the index is maintained on your machine itself.

**Comment by nisha-bito** [comment]
hi @JackOman69 ,

We hope the above information is helpful for you. 
In case you have any further questions, please do let us know.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @JackOman69 ,

this issue will be closed now. Please feel free to open a new issue in case you face any further issues. 

Thanks,
nisha
