### ISSUE TITLE
Suggestion: add some customization settings

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#16]
Some suggestions that can enhance the enjoyment of using Bito AI.

## Dark and light color modes

Bito AI uses a dark background by default, which looks good when the IDE is using a dark theme.

When the IDE uses a light theme (which I'm sure some people would prefer), Bito AI still has a dark background, which is slightly less 'integrated'.

See VSCode's "Light+" theme for the color scheme.

<details><summary>Example</summary>
<p>

![Dark](https://user-images.githubusercontent.com/39868412/226072989-bd20a402-3a0a-423e-ac11-b48f3984004d.png)

![Light](https://user-images.githubusercontent.com/39868412/226073016-2b98283e-3fe2-40bf-80f8-c7115fd9d118.png)

> Theme: [Vim VSCode Theme](https://github.com/Harry-Hopkinson/vim-vscode-theme) 😊

</p>
</details> 

## Customising the accent color
Blue is great, of course, but it would be even better if there were more color options available. (e.g. red, orange, yellow (with black text), green, aqua, purple, pink 😊)

**Comment by bitoandy** [comment]
Thanks @monicfenga for the suggestion, our UX team is working on this, will keep you posted on the changes and when it will be available.

**Comment by henryjw** [comment]
I second the request for a light mode. All 6 of us light theme users would greatly appreciate it 🙏

**Comment by Termonna** [comment]
The society of developers with astigmatism would be very grateful for a light theme 🙏
We find it extremely uncomfortable to read thin light letters on a dark background because they double and blur.

**Comment by monicfenga** [comment]
> Thanks @monicfenga for the suggestion, our UX team is working on this, will keep you posted on the changes and when it will be available.

I tried out the new color mode today, and the "adaptive" mode is **super awesome**!!!

**Comment by nisha-bito** [comment]
Thanks for the feedback @monicfenga .

**Comment by nisha-bito** [comment]
@Termonna @henryjw : please try our new set of feature e.g. Light and dark themes, smart intention interpretation, font size customization in IDE plugin.
