### ISSUE TITLE
First time using this plugin in vscode, the workspace will generate .vscode/settings.json

### ISSUE THREAD

**Issue by tomgao365** [gitbito/bitoai#173]
First time using this plugin in vscode, the workspace will generate` .vscode/settings.json`, regardless of whether the user settings are set to `editor.inlineSuggest.showToolbar`

```json
{
  "editor.inlineSuggest.showToolbar": "onHover"
}
```

![image](https://github.com/gitbito/bitoai/assets/13798931/94f050a7-9015-48e5-afae-18325b92682e)

After many attempts, disabling other plugins, only `bito` will cause this problem

![image](https://github.com/gitbito/bitoai/assets/13798931/4b972326-c3c8-49bf-956a-3b4ba32e5ea4)

**Comment by nisha-bito** [comment]
hi @tomgao365 ,

Thanks for reporting this. We will consider this.

Thanks,
nisha

**Comment by nisha-bito** [comment]
hi @tomgao365 ,

We have considered your suggestion and incorporated it in Bito release 1.2.7.
Thank you, Happy Bito !!!! 

Thanks,
nisha
