### ISSUE TITLE
It`s a BUG or other?

### ISSUE THREAD

**Issue by Hoper-Q** [gitbito/bitoai#177]
I received a message, I ask any question the reply is this. And Intelligence is same.

We love that you love Bito’s AI Code Completions!  
You have hit your limit for AI Code Completions per day on your plan.  
To receive more Completions, please upgrade your plan or contact support@bito.ai

But I remember this. Please tell me why?
![image](https://github.com/gitbito/bitoai/assets/52480108/9821a284-69ad-40b0-a371-eb928b02907a)

**Comment by amargoel98** [comment]
Hi, AI is quite expensive to offer and as a startup we want can't sustain the costs of unlimited AI usage. So we have put in some limits to give people a chance to try it out before thinking about upgrading. Our chat limits of 20 per day only affect about 10% of users. So, for the most part, our free plan is similar to a few months ago for 90% of users.

**Comment by Hoper-Q** [comment]
> Hi, AI is quite expensive to offer and as a startup we want can't sustain the costs of unlimited AI usage. So we have put in some limits to give people a chance to try it out before thinking about upgrading. Our chat limits of 20 per day only affect about 10% of users. So, for the most part, our free plan is similar to a few months ago for 90% of users.  

I can understand. But I think you should change your license.

**Comment by amargoel98** [comment]
You are right. We are updating this.
