### ISSUE TITLE
ERROR: We love that you love Bito's AI Chat! You have hit your daily chat limit on your plan. 

### ISSUE THREAD

**Issue by wangyexiang** [gitbito/bitoai#178]
"We love that you love Bito's AI Chat! You have hit your daily chat limit on your plan. Please upgrade your plan to have access to Unlimited chats. Please visit https://bito.ai/pricing for more details." How to fix it?

**Comment by nisha-bito** [comment]
hi @wangyexiang ,

If you are using Free account, we have a limit of 20 request per day. You can check on https://bito.ai/pricing  page information about Free account vs Paid account. 

You can upgrade to Paid account using 
1. Bito plugin inside VS code or JetBrains -> click on the Upgrade button at top of the Bito plugin. 
2. using WEB URL- https://alpha.bito.ai/home/settings/bito-premium/billing. Login using the email id you use for Bito. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @wangyexiang ,

Please let us know if you have any further questions.
This issue will be closed after few days, feel free to re-open the issue if you need any further assistance. 

Thanks,
Nisha

**Comment by wangyexiang** [comment]
> hi @wangyexiang ,
> 
> Please let us know if you have any further questions. This issue will be closed after few days, feel free to re-open the issue if you need any further assistance.
> 
> Thanks, Nisha
Can you set a limit of 50 request per day?

**Comment by nisha-bito** [comment]
Hi @wangyexiang ,

I am afraid the Free plan doesn't allow that. 
You can upgrade to Paid plan and you will get higher request per day with paid plan.

thanks,
nisha
