### ISSUE TITLE
crash a few seconds after launching the extension

### ISSUE THREAD

**Issue by FoxWind-coder** [gitbito/bitoai#180]
Type: <b>Bug</b>

try to use the extension

Extension version: 1.2.7
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.91GB (31.05GB free)|
|Process Argv|--crash-reporter-id ce3c941d-cefd-4db9-b1c9-013f6b4aaea6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
89544117:30613380
a9j8j154:30646983
0bi6i642:30917235
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t3:30927821

```

</details>

**Comment by bitoandy** [comment]
Thanks @FoxWind-coder for reporting this.

Can you provide more details on when exactly you see the crash, like when you open the Bito panel or use any Bito functionality. If you just install Bito extension and don’t use it did you see any crash?

We are also analyzing the issue on our end and will keep you posted on the updates. And might also reach out if we need some additional logs.

**Comment by nisha-bito** [comment]
hi @FoxWind-coder ,

We are closing issue in absence of any response, feel free to re-open ticket if you are still facing issue. 

Thanks,
Nisha
