### ISSUE TITLE
I have a question I'd like to ask.

### ISSUE THREAD

**Issue by 18801151992** [gitbito/bitoai#182]
I saw this plugin seems to be using the shell of IDEA, loading a URL inside. I am developing a similar feature, using JBCefBrowser to load a URL. After successful loading and opening the address, typing in the input box results in a 'pending edit' status. May I know what could be causing this issue? Or if it's not implemented with JBCefBrowser, could you inform me what method is used? Thank you.
<img width="1407" alt="image" src="https://github.com/gitbito/bitoai/assets/25807952/aaeddc19-d0a6-4362-b49f-915e23cdbe0c">

**Comment by nisha-bito** [comment]
hi @18801151992 ,

We are using JBCefBrowser. For UI, we are using Angular. 

Thanks,
Nisha
