### ISSUE TITLE
Codes are not getting added in the editor format

### ISSUE THREAD

**Issue by jamsheedcorra** [gitbito/bitoai#183]
Most of the portions of the AI Generated codes are not showing in editor format so not able to copy or insert to the selected file. 
Attached screenshot of the issue. 
Device: Mac OS Sonoma, Version: 14.3

<img width="627" alt="Screenshot 2024-02-12 at 4 10 58 PM" src="https://github.com/gitbito/bitoai/assets/149354042/f7836800-6312-43ad-87b7-b4cda2054eae">

**Comment by nisha-bito** [comment]
hi @jamsheedcorra ,

Thanks for reporting the issue, we are looking into it. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
Hi @jamsheedcorra ,

The reported issue has been fixed. Please verify if the fix is working fine for you. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @jamsheedcorra ,

I hope the issue is resolved for you in th latest version of Bito. Please report us in case of any further issue.

Thanks,
Nisha
