### ISSUE TITLE
"Accept Word" not working in Jetbrains Rider

### ISSUE THREAD

**Issue by BewaAutomatisierung-RD** [gitbito/bitoai#184]
With activated inline code completion  I get suggestions and a menu where I can move to next/previous suggestion or Accept or Accept Word.  "Accept Word" is the feature I got Bito.AI for because auto complete suggestions often contain more than I really want and the possibility to accept word by word up to where I want to go on with my own code was very appealing to me. Unfortunately this feature is not working. It's not accepting any word neither with Ctrl+RightArrow nor by clicking on "Accept Word" in the Menu. 
Another Problem is that the keyboard shortcut for "Accept word" cannot be changed in the Rider settings.

**Comment by nisha-bito** [comment]
hi @BewaAutomatisierung-RD ,

Thanks for reporting. 
Apology for the confusion. Accept Word feature is not supported yet. You can Accept whole suggestion using "Tab". 

Thanks,
nisha

**Comment by BewaAutomatisierung-RD** [comment]
Hello @nisha-bito ,
too bad.  That made me cancel my subscription.  That feature was the main point for me to try bito as alternative to Github Copilot.

**Comment by nisha-bito** [comment]
hi @BewaAutomatisierung-RD ,

Based on your feedback, we have hide the Accept word button until we support it. 
Hope you can still use Bito for other features. 

Thanks,
Nisha
