### ISSUE TITLE
Bito dosn't work with android Studio Iguana | 2023.2.1

### ISSUE THREAD

**Issue by adhamalaa111** [gitbito/bitoai#191]
![blank](https://github.com/gitbito/bitoai/assets/49401600/426b16fb-66d1-413b-b3ea-c387392e8e77)
Bito dosn't work with android Studio Iguana | 2023.2.1 Though i changed the default Boot runtime settings in Android Studio to a version that supports the JCEF browser and get Bito running on Android Studio and
 ide.browser.jcef.sandbox is enable

**Comment by nisha-bito** [comment]
hi @adhamalaa111 ,

Please go through document https://docs.bito.ai/support-and-questions/troubleshooting and make the settings accordingly to make Bito work in Android Studio.

If you face any further issue, do let us know.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @adhamalaa111 ,

Please let us know if you can use Bito now ? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @adhamalaa111 ,

This issue will be closed now, however please re-open the issue in case you still facing issue in using Bito. 
I hope the documentation helped you? 

Thanks,
Nisha
