### ISSUE TITLE
Stuck on "Going through your code..." seemingly indefinitely

### ISSUE THREAD

**Issue by Algomorph** [gitbito/bitoai#193]
The following query makes BitoAi get stuck on "Going through your code..." for over 5 minutes:

> Question :
> 
> I'm trying to build the AWS C++ SDK (aws-sdk-cpp) dependency for my project via the following cmake command in Bazel: 
> ``` 
> cmake( 
>     name = "aws-sdk-cpp_cmake_ubuntu", 
>     build_args = [ 
>         "--verbose", 
>         "--",  # <- Pass remaining options to the native tool. 
>         # https://github.com/bazelbuild/rules_foreign_cc/issues/329 
>         # there is no elegant paralell compilation support 
>         "VERBOSE=1", 
>         "-j 4", 
>     ], 
>     cache_entries = { 
>         "CMAKE_BUILD_TYPE": "Release", 
>         "BUILD_ONLY": "s3",  # core builds always 
>         "ENABLE_TESTING": "OFF", 
>         "AUTORUN_UNIT_TESTS": "OFF", 
>         "BUILD_SHARED_LIBS": "OFF", 
>         "MINIMIZE_SIZE": "ON", 
>         "CMAKE_POSITION_INDEPENDENT_CODE": "ON", 
>         "FORCE_SHARED_CRT": "OFF", 
>         "SIMPLE_INSTALL": "OFF", 
>         "CMAKE_CXX_FLAGS": "-D_GLIBCXX_USE_CXX11_ABI=1 -Wno-error=deprecated-declarations -Wuninitialized", 
>     }, 
>     env = { 
>         "HTTP_PROXY": "{http_proxy}",
>         "HTTPS_PROXY": "{https_proxy}",
>     }, 
>     lib_source = ":all_srcs", 
>     out_lib_dir = "lib", 
>     # linking order 
>     out_static_libs = select({ 
>         "//conditions:default": [ 
>             "linux/intel64/Release/libaws-cpp-sdk-s3.a", 
>             "linux/intel64/Release/libaws-cpp-sdk-core.a", 
>         ], 
>         ":dbg": [ 
>             "linux/intel64/Debug/libaws-cpp-sdk-s3.a", 
>             "linux/intel64/Debug/libaws-cpp-sdk-core.a", 
>         ], 
>     }) + [ 
>         "libaws-crt-cpp.a", 
>         "libaws-c-s3.a", 
>         "libaws-c-auth.a", 
>         "libaws-c-cal.a", 
>         "libaws-c-http.a",
>         "libaws-c-io.a", 
>         "libs2n.a", 
>         "libaws-c-compression.a", 
>         "libaws-c-sdkutils.a", 
>         "libaws-c-mqtt.a", 
>         "libaws-c-event-stream.a", 
>         "libaws-checksums.a", 
>         "libaws-c-common.a", 
>     ], 
>     tags = ["requires-network"], 
>     visibility = ["//visibility:public"], 
>     alwayslink = False, 
> ) 
> cc_library( 
>     name = "aws-sdk-cpp_ubuntu", 
>     visibility = ["//visibility:public"], 
>     deps = [ 
>         ":aws-sdk-cpp_cmake_ubuntu", 
>     ], 
>     alwayslink = False, 
> ) 
> ``` 
> The above cmake command and cc_library rule are both defined within a BUILD.bazel file that is generated via the following repository_rule in Bazel: 
> ``` 
> def aws_sdk_cpp(): 
>     aws_sdk_cpp_repository(name = "_aws_sdk_cpp") 
>     new_git_repository( 
>         name = "aws-sdk-cpp", 
>         remote = "[https://github.com/aws/aws-sdk-cpp.git"](https://github.com/aws/aws-sdk-cpp.git), 
>         build_file = "@_aws_sdk_cpp//:BUILD.bazel", 
>         tag = "1.11.268", 
>         init_submodules = True, 
>         recursive_init_submodules = True, 
>         # https://github.com/bazelbuild/bazel/issues/374 
>         # issues with ASCI handling of file_test.c *xample file.txt in bazel 
>         patch_cmds = ["find . -name '*xample.txt' -delete"], 
>     ) 
> def _impl(repository_ctx): 
>     http_proxy= repository_ctx.os.environ.get("http_proxy","") 
>     https_proxy= repository_ctx.os.environ.get("https_proxy","") 
>     #Label("//mediapipe/presage/3rd_party/openssl:BUILD.openssl.bazel") 
>     build_file_label = Label("//mediapipe/presage/3rd_party/aws-sdk-cpp:BUILD.aws-sdk-cpp.bazel") 
>     build_file_content = repository_ctx.read(build_file_label) 
>     # Note we need to escape curly braces '{...}' by doubling them due to call to format 
>     build_file_content = build_file_content.replace("{", "{{").replace("}", "}}") 
>     repository_ctx.file( 
>         "BUILD.bazel", 
>         build_file_content.format(http_proxy= http_proxy,https_proxy= https_proxy),
>     ) 
> aws_sdk_cpp_repository = repository_rule( 
>     implementation = _impl, 
>     local = False, 
> ) 
> ``` 
> The `cmake` command and `cc_library` rule are both originally defined in the `//mediapipe/presage/3rd_party/aws-sdk-cpp:BUILD.aws-sdk-cpp.bazel` template file. 
> Unfortunately, AWS C++ SDK makes many modifications to files in its source directory. Because of this, CMake code in AWS C++ SDK such as  
> ``` 
>     configure_file( 
>         "${CMAKE_CURRENT_SOURCE_DIR}/include/aws/core/VersionConfig.h.in" 
>         "${CMAKE_CURRENT_SOURCE_DIR}/include/aws/core/VersionConfig.h" 
>         NEWLINE_STYLE UNIX) 
> ``` 
> Causes the following error:  
> CMake Error at src/aws-cpp-sdk-core/CMakeLists.txt:21 (configure_file): 
>   Read-only file system 
> I'm guessing that, due to Bazel's sandboxing / hermetic builds, it disallows CMake access to the source directory. How can I get around this and successfully build the `aws-sdk-cpp_ubuntu` dependency?

Relevant context: I'm pasting my code directly into the prompt, because, based on previous behavior, I don't think the code context feature works correctly on Bazel project (i.e. see Bazel plugin for CLion). I've referenced files in my project before, but BitoAI didn't seem to know what I was referring to.

Version information:
```
CLion 2023.3.4
Build #CL-233.14475.31, built on February 13, 2024
Licensed to Presage Security, Inc / Gregory Kramida
Subscription is active until November 19, 2024.
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-25-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  A move tab left and right using the keyboard plugin - by momomo.com (12.550)
  co.bito.bito-intellij (1.2.8)
  com.mikejhill.intellij.movetab (2.1.1)
  ru.adelf.idea.dotenv (2024.1)
  kemoke.net.cssmodule (1.1)
  com.haulmont.rcb (233.13135.65)
  com.google.idea.bazel.clwb (2024.01.30.0.1-api-version-233)
Current Desktop: ubuntu:GNOME
```

**Comment by nisha-bito** [comment]
hi @Algomorph ,

We are looking into it. Thanks for reporting.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
Hi @Al,

Can you please upgrade to Bito plugin version 1.3.0 and let us know if you still face the issue? 

Can you share the logs to further investigate it if you still face the issue? 


1. For VSCode  
 1.1 - Help --> Toggle Developer Tools --> Console  --> Right click and use menu "Save as".

2. For JB  
 2.1 - Help --> Find Action --> type Bito  under Action --> select "Bito: Open dev tools" -->  Console --> Right click and use menu "Save as".
 2.2 - Help --> Collect Logs and Diagnostic Data --> Show in folder and It will give you the log in zip format.

Thanks,
Nisha

**Comment by Algomorph** [comment]
I tried the question again. By the way, I noticed simple copy/paste doesn't copy the ``` tick marks that I use to delimit code blocks from the question text, these I had to re-insert those manually. I'm attaching the text of the question with the tick marks for convenience: 
[BitoAiQuery.txt](https://github.com/gitbito/bitoai/files/14774324/BitoAiQuery.txt)

With the tick marks, I'm getting a different output from Bito:
"Could not find a relevant data or information to answer the question."
(By the way, the article "a" shouldn't be in the above sentence.)

This happens immediately after I submit the question. I had the repository state saved in a separate branch, so that shouldn't have affected the outcome.

The action
```
Console --> Right click and use menu "Save as".
``` 
doesn't actually open any file saving dialog for me on Linux (Ubuntu 22.04), so I simply copy/pasted the contents to this text file: 
[BitoConsole.txt](https://github.com/gitbito/bitoai/files/14774329/BitoConsole.txt)

Here are the CLion logs for the tickmark attempt: [clion-logs-20240327-0955581975491376482003209.zip](https://github.com/gitbito/bitoai/files/14774310/clion-logs-20240327-0955581975491376482003209.zip)

_Without_ the tick marks (which _were_ there in the query when I originally reported this issue, and I tried multiple times that day), I'm still getting "Going through your code..." blinking  for a long time, but then I finally get "Could not find a relevant data or information to answer the question.", which did not happen previously.

When I tried to save the console output again, the JCEF DevTools dialog came up frozen right away, and I couldn't do anything:
![image](https://github.com/gitbito/bitoai/assets/1050606/2cb07b92-f64f-4ca6-9c32-22ada011c590)

**Comment by nisha-bito** [comment]
hi @Algomorph ,

Error "Could not find a relevant data or information to answer the question.", indicates that the index is not proper/correpted. 
Can you go to index listing and click on 3 dots and delete the index. 
<img width="422" alt="Screenshot 2024-03-28 at 12 40 12 PM" src="https://github.com/gitbito/bitoai/assets/123052606/90c68d0a-025f-442e-a637-2cd8e4577bed">

After deleting the index, close IDE and open it again. It will ask you to index it again, please let the index happen again and try to query Local code again.

Let us know if this works for you. 

thanks,
Nisha

**Comment by Algomorph** [comment]
Thanks for your reply, @nisha-bito ,

Unfortunately, regenerating the Bito index and reloading the application didn't accomplish anything in my case. This is all in the same project. For context, the question "Are you looking for an answer based on your current project?" didn't come up that time at all, and the response was immediate. I pasted all the relevant content into the question at all, so the answer should be "no", but it doesn't work either way.

Here's the link to the session: https://share.bito.ai/static/share?aid=0f6b8182-2db8-4024-adbe-8562816b2146
Let me know if you can't view it.

To be frank, I don't think the index / project context questions don't work at all for [Bazel](https://plugins.jetbrains.com/plugin/9554-bazel-for-clion) projects in CLion. I've tried many times, but could never get anything meaningful when clicking "Yes" to the question "Are you looking for an answer based on your current project?". Not sure if it's related to Bazel at all. Is indexing done based on the actual code on the hard drive, or is it only done for open-source projects on github and such?

**Comment by Algomorph** [comment]
I'll make a new issue for the Bazel project indexing, since I don't think the indexing is relevant to the original problem here.

**Comment by nisha-bito** [comment]
hi @Algomorph ,

We have responded the RCA for indexing issue in https://github.com/gitbito/bitoai/issues/198. Please suggest if we can close this ticket now? 

Thanks,
Nisha

**Comment by Algomorph** [comment]
The indexing issue is unrelated to this bug. As I mention in an earlier post here, even when answering "no" to the question "Are you looking for an answer based on your current project?", BitoAI doesn't return an appropriate response. I deliberately phrased the original question such that it doesn't need to rely on the index.

**Comment by nisha-bito** [comment]
hi @Algomorph ,

Can you please share the question where you didnt got correct/appropriate answer when you selected to get a non-LCA answer? 
Please also confirm for the example, you were using Basic or Advance model.
This will help us analyse this in detail.

Thanks,
Nisha

**Comment by Algomorph** [comment]
This current thread _is_ about the non-LCA issue (i'm assuming LCA stands for 'Local Code Analysis'). Please review thread history.

I've been using the `Advanced` model here and any other. "Could not find a relevant data or information to answer the question." is the best I ever got, after a BitoAI upgrade, which I'm guessing shouldn't happen. Originally, it was "Going through my code" indefinitely. The only reason I even mention the LCA information is that the outcome doesn't change whether or not LCA is used.

**Comment by nisha-bito** [comment]
hi @Algomorph ,

We are already working on the fix for Bazel plugin and the fix shall be available in couple of days.
I will confirm you when the new release is done with this fix.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Algomorph ,

We have released the fix along with Bito 1.3.2 version. please let us know if this works for you. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Algomorph ,

Please let us know if the fix is working fine for you. 
This ticket will be closed now, feel free to re-open it in case the fix is not working for you. 

Thanks,
Nisha

**Comment by Algomorph** [comment]
@nisha-bito thanks, Bazel support does seem to work now. Utility has been very limited so far, but I will keep evaluating Bito.

**Comment by nisha-bito** [comment]
Thanks @Algomorph ,

Please do keep us posted with your feedback on Bito.
