### ISSUE TITLE
Whether the default language can be switched

### ISSUE THREAD

**Issue by Lron-boy** [gitbito/bitoai#20]
Whether it generates comments or interprets code, it is all in English. Whether subsequent versions can support switching languages

**Comment by monicfenga** [comment]
Temporary solution: You can use **your language** to ask the bito to write a comment by first writing what you want the bito to do, e.g. "Please write a comment for this code", then putting in a colon, then hitting `shift + return` twice, then pasting the code, finally sending it out.

```
Q:
请为这段代码撰写注释：(translate: Please write comments for this piece of code)

function stately_format_number($number = 0,$precision = 2) {
	$number = intval($number);
	$suffix = '';
	if ($number >= 1000 && $number < 1000000) {
		// 一千到一百万
	  $number = round($number / 1000, $precision);
	  $suffix = 'k';
	} elseif ($number >= 1000000 && $number < 1000000000) {
		// 一百万到十亿
	  $number = round($number / 1000000, $precision);
	  $suffix = 'm';
	} elseif ($number >= 1000000000 && $number < 1000000000000) {
		// 十亿到一兆(一万亿)
	  $number = round($number / 1000000000, $precision);
	  $suffix = 'b';
	} elseif ($number >= 1000000000000) {
		// 一兆以上
	  $number = round($number / 1000000000000, $precision);
	  $suffix = 't';
	}
	return $number . $suffix;
}
}

A:
这段代码定义了一个名为stately_format_number的函数，用于格式化数值为带有单位的字符串。参数$number表示需要格式化的数字，$precision表示保留的小数位数，默认值为2。根据数字的大小，函数会将数字转换为带有k、m、b、t等单位的字符串，方便阅读和比较。注释详细说明了数字与单位的转换范围，使得函数的功能易于理解和使用。

Answer Translate:
This code defines a function called stately_format_number that formats a number into a string with units. The argument $number indicates the number to be formatted and $precision indicates the number of decimal places to retain, with a default value of 2. Depending on the size of the number, the function will convert the number to a string with units such as k, m, b, t, etc. for easy reading and comparison. Comments detail the range of numbers and units to be converted, making the function easy to understand and use.
```

**Comment by nisha-bito** [comment]
hi @Lron-boy @monicfenga :
With our new release [1.0.132] we have memory, so if you have an answer in English, you can ask it to give you the answer in any other Language as your next question.  
Request you to please try version 1.0.132 and let us know if this works for you. 

Thanks,
Nisha

**Comment by monicfenga** [comment]
> if you have an answer in English, you can ask it to give you the answer in any other Language as your next question.
i'm using this trick, and it was super effective

**Comment by nisha-bito** [comment]
Great. @monicfenga . 
Let us know if you face any other issues while using Bito. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
Sounds great @monicfenga .

**Comment by bitomukesh** [comment]
closing this issue.
