### ISSUE TITLE
VS Code plugin: quick standard action for docstings

### ISSUE THREAD

**Issue by wowkalucky** [gitbito/bitoai#200]
## Story

A couple of pre-defined quick actions in a context menu are already available.
I can see, that an even more frequently used operation, compared to the `Generate Comment` is **docstrings generation** (function, class, module, etc.).

![image](https://github.com/gitbito/bitoai/assets/2472913/393cc80a-8e68-40f7-aa92-d7710450e380)

## Request

Add the corresponding `Generate docstring` action available in the context menu.

**Comment by nisha-bito** [comment]
hi @wowkalucky ,

You can create your own Custom template which will be available always for your use via context menu and also via templates.
Find the documentation related to the same - https://docs.bito.ai/templates/custom-prompt-templates, let us know if this solves your problem ? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @wowkalucky ,

Can you confirm if you are able to create your own template for this? Let us know if this si working for you? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
Thanks for confirming. 

Please let us know if you face any more issues or have any other questions. 

Thanks,
Nisha
