### ISSUE TITLE
I can't sign in

### ISSUE THREAD

**Issue by HU75** [gitbito/bitoai#201]
OS: Windows 10
Bito version: 1.3.1
VS code version: x64-1.52.1

I connected to the virtual machine(ubuntu 20.04) remotely via ssh, and the bito was also installed in ssh mode. And I have set the port. But there was no input in the sign up window, when I type. There's no reaction.

![image](https://github.com/gitbito/bitoai/assets/75312764/d40e0d12-2eda-4ea6-8a3e-057d4f7a40ea)

**Comment by HU75** [comment]
Hi Nisha,

Thank you for your reply. I can confirm that I set up the port number in the PORTS screen, which is same as the port in the notification.

My email address is hushaygo@163.com.

The log for vscode has been added in the attachment.

Thanks,
HU

[vscode-app-1712119305682.log](https://github.com/gitbito/bitoai/files/14846802/vscode-app-1712119305682.log)

**Comment by nisha-bito** [comment]
hi @HU75 ,

We see error "Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope" in the logs. This is an VS code error which comes sometime while a plugin is loaded. When this error comes, the plugin doesnt function properly. 

Request you to reload the plugin or close and open the VS code and try again once. If the error still persists please let us know. 

Also please confirm when you are not able to type anything in the input box, are u able to paste content in the input? 

Thanks,
Nisha

**Comment by HU75** [comment]
Hi Nisha,

Thank you for your analysis and help. I retried a few times and was able to log in and use bito successfully.

Thanks,
HU
