### ISSUE TITLE
Error plugin

### ISSUE THREAD

**Issue by AlexJMcloud** [gitbito/bitoai#202]
PhpStorm 2024.1 Build #PS-241.14494.237, built on March 27, 2024 

plugin version 1.3.1

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'co.bito.intellij.actions.InsertCodeIntoBito' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: co.bito.bito-intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by nisha-bito** [comment]
hi @AlexJMcloud ,

JetBrains API has released a new version of an API recently which is not compatible with 2024.1. We are working with JB team to find the best option to implement the latest API as per JB guideline. 
We shall release a fix as soon as possible for this. 

**Please note**: this exception, should not cause any functionality break. 

Thanks,
nisha

**Comment by Essienb** [comment]
Is there still an issue with Bito vs 1.3.2 in Intellij_2023.1.1? Mine has refused to load up and when it does load, it keeps spinning and does not allow me to use the Indexing.

**Comment by Essienb** [comment]
Hello,

There are no logs to share. I try to start the plugin in my intellij but
the page where you are supposed to be able to type in your
comments/questions is blank. 2 days now I cannot use.

Regards,
Essien Bassey

**Comment by nisha-bito** [comment]
Hi ,

Sorry to hear that you are not able to use Bito.

Can you help su with the email you are using to login into Bito? 

Please use below steps for get the logs for IntelliJ - 

1. For JB ==> Help --> Find Action --> type Bito  under Action --> select "Bito: Open dev tools" -->  Console --> Right click and use menu "Save as".
2. For JB ==> Help --> Collect Logs and Diagnostic Data --> Show in folder and It will give you the log in zip format.

Thanks,
Nisha

**Comment by Essienb** [comment]
I tried step 1 and got nothing in the console. So no logs to send.

**Comment by nisha-bito** [comment]
Hi,

Can you please send logs from #2? 

Thanks,
Nisha

**Comment by Essienb** [comment]
No. But I've un-installed it because it's failing to start for me.

**Comment by nisha-bito** [comment]
hi @Essienb ,

Very sorry to hear that you are still facing issue with Bito. 
Please suggest a convenient time to sync up over an call. We would like to resolve the issue at your end so that you can continue using Bito. 

In the mean time, you can also delete the existing indexes -> Restart IDE -> and index the repo again. This shall resolve if you have any issue with old index. 

Thanks,
Nisha

**Comment by Essienb** [comment]
I have deleted all the indexes I have in Repo, restarted my IDE but still
can't get Indexing to work.

Share a link privately to me for connecting.

**Comment by nisha-bito** [comment]
hi @Essienb ,

Please send an email on support@bito.ai, so that we can send you an invite to connect over an call.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
Thanks, have a shared an invite.

**Comment by nisha-bito** [comment]
hi @Essienb ,

We resolved issue over call. For any further problem, do write us at support@bito.ai.

**Comment by Essienb** [comment]
Thank you but note that for me to use Bito, I always have to close and
re-open my Intellij more times than usual. So the issue is not fully
resolved, what we did is a stop gap to the best of my knowledge.

When will there be a lasting solution?

Best regards.
