### ISSUE TITLE
How do I switch models after opening a 10x plan

### ISSUE THREAD

**Issue by Zhe-xing-sun** [gitbito/bitoai#204]
How to switch back to the 3.5 model in use after opening the 10X developer program, instead of forcing the 4.0 model, is the 4.0 model used after 400 requests to use the 3.5 model?

**Comment by bitoandy** [comment]
Please refer to the screen shot with instructions to use "Basic" model (GPT-3.5 and similar models).
![Screenshot 2024-04-27 at 12 57 18 PM](https://github.com/gitbito/bitoai/assets/125080245/d65bc854-3eb0-4796-8965-43f1e7d906b1)
![Screenshot 2024-04-27 at 12 59 15 PM](https://github.com/gitbito/bitoai/assets/125080245/35dc6308-8dfa-47f6-9b0e-e01fe56551bc)

The screen shots are provided for VS Code, you can click on the same icons in case of JetBrains IDE in the Bito panel for selecting "Basic" model (GPT-3.5 and similar models).

**Comment by Zhe-xing-sun** [comment]
Thank you for your answer，bro

**Comment by bitoandy** [comment]
Thanks @Zhe-xing-sun , closing this issue.
