### ISSUE TITLE
How can I choice full line suggestions tool?

### ISSUE THREAD

**Issue by ChandlerBent** [gitbito/bitoai#205]
I love to use bito chat.

I can not use pycharm full line suggestion when I enable bito plugin.

Can bito add feature that I can choice which full line suggestion tool I want to use?

**Comment by nisha-bito** [comment]
hi @ChandlerBent ,

JetBrains Full line completion feature is using same API underline to show suggestion as JetBrain's API which is being used by Bito and many other plugins. 
This is the reason why JetBrains has release the feature with below condition -
1. If any plugin is using Full Line completion API - then JetBrains is disabling its Full line completion automatically. 
2. If user wants to sue JetBrains Full line feature, it can be done by disabling the plugin temporarily. 

We have been in touch with JetBrains team to understand, if there is any better option, but unfortunately JetBrains suggested that above is the best option as of now. 

Thanks,
Nisha

**Comment by ChandlerBent** [comment]
> hi @ChandlerBent ,
> 
> JetBrains Full line completion feature is using same API underline to show suggestion as JetBrain's API which is being used by Bito and many other plugins. This is the reason why JetBrains has release the feature with below condition -
> 
> 1. If any plugin is using Full Line completion API - then JetBrains is disabling its Full line completion automatically.
> 2. If user wants to sue JetBrains Full line feature, it can be done by disabling the plugin temporarily.
> 
> We have been in touch with JetBrains team to understand, if there is any better option, but unfortunately JetBrains suggested that above is the best option as of now.
> 
> Thanks, Nisha

Thank you for reply.
