### ISSUE TITLE
Add Spaces between the code

### ISSUE THREAD

**Issue by PierrunoYT** [gitbito/bitoai#21]
The Code is written without spaces between the lines and parts of the code.

**Comment by bitoandy** [comment]
Hi @PierrunoYT ,


We are working on the issue and will provide an update on the fix.

**Comment by nisha-bito** [comment]
hi @PierrunoYT ,

Version 1.1.1 is available in marketplace. Please download and check if this has resolved reported issue. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @PierrunoYT ,

Version 1.1.2 is also available in marketplace. Please download and check if this has resolved reported issue.
Please note, this ticket will be auto closed in few days, please feel free to create a new ticket in case the problem still exists. 

Thanks,
Nisha
