### ISSUE TITLE
Cannot login to Bito when using WSL via VSCode

### ISSUE THREAD

**Issue by peachypeachyy** [gitbito/bitoai#215]
I am not able to login to BitoAI when I am using WSL on VSCode.
Works fine when I am not using WSL.

Current version of Bito: `1.3.4`
Current version of Ubuntu as WSL OS: `Ubuntu 22.04.3 LTS`
Current version details of VSCode:
```
    Version: 1.90.2 (user setup)
    Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
    Date: 2024-06-18T22:34:26.404Z
    Electron: 29.4.0
    ElectronBuildId: 9728852
    Chromium: 122.0.6261.156
    Node.js: 20.9.0
    V8: 12.2.281.27-electron.0
    OS: Windows_NT x64 10.0.22631
```

I have attached the console logs from the Dev tools window
[vscode-app-1719224644513.log](https://github.com/user-attachments/files/15953879/vscode-app-1719224644513.log)

**Comment by nisha-bito** [comment]
Hi @peachypeachyy ,

Can you try to connect to VS code using SSH if you are connecting to a remote machine? 
WSL works when you connect to a local and SSH works when you try to connect to a remote machine.
 
Follow below steps to connect via SSH –
Connect VS code via SSH - https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse
If the SSH connection is enabled and Bito is started, the extension will execute the built-in command provided by the Remote-SSH extension called 'Forward a Port'.
Once prompted, please enter the port number which you see in Bito notification to be forwarded. The Remote-SSH extension API will then execute, and the Ports console will become active.
 
Reference video - https://www.loom.com/share/29af0fa7133b4173a1c51b1ee1a71095

Thanks,
Nisha

**Comment by peachypeachyy** [comment]
Yes ok, this works with SSH, but my WSL machine is inside my laptop itself, it's quite non-intuitive for me to ssh into a machine which is already running inside my laptop, I have to un-necessarily make it a SSH server, enable key-based authentication and expose port 22. My IP of WSL machine may change periodically as well.

Can this not be done through WSL?

**Comment by trackds** [comment]
I had the same problem.
I have a temporary solution here.
Open the ~/.vscode-server/extensions/bito.bito-1.3.7/dist/vscode/extension.js
Find ` ` ` if (connectionType.toLowerCase() === extensionConstants_1.VSCODE_CONNECT_WSL) {\n            HOST = IP.address(); ` ` `
Replace ```HOST = IP.address()``` with ```HOST = "localhost"```, save and restart vscode, and it should work fine

**Comment by nisha-bito** [comment]
Thank you for the suggestion @trackds. Appreciate it.
