### ISSUE TITLE
Error when using Bito extension on Intellij in more than one workspace at the same time

### ISSUE THREAD

**Issue by GuiRodriguero** [gitbito/bitoai#22]
If I open workspaces/projects A and B and try to use Bito on workspace A, it works fine. But if i open the extension on workspace B, it does not work anymore on either workspaces

**Comment by bitoandy** [comment]
Hi @GuiRodriguero ,

we are looking into the issue and provide an update soon. Can you also drop an email on support@bito.ai with screen shots will help us get some more details to get to the issue quickly.

**Comment by bitoandy** [comment]
Thanks for the details, we will use the scenario mentioned and work on reproducing the issue and identifying the fix.

________________________________

**Comment by bitomukesh** [comment]
closing the issue for now.
