### ISSUE TITLE
cant use in Android Studio Koala

### ISSUE THREAD

**Issue by yuexuanchen** [gitbito/bitoai#220]
I have correctly installed and enabled bito version 1.4.0, but I cannot find or launch it in my Android Studio.
Android Studio Koala | 2024.1.1 Patch 1

**Comment by nisha-bito** [comment]
hi @yuexuanchen ,

Please follow below documentation to enable and use Bito in Android studio.

1. https://docs.bito.ai/support-and-questions/troubleshooting#id-1-bito-jetbrain-extension-doesnt-work-in-android-studio
2. https://docs.bito.ai/support-and-questions/troubleshooting#bito-doesnt-load-and-show-a-blank-page-when-installed-in-android-canary

Thanks,
Nisha

**Comment by yuexuanchen** [comment]
change the default Boot runtime settings in Android Studio to a version that supports the JCEF browser and get Bito running on Android Studio
