### ISSUE TITLE
Deleting session locally doesn't delete a previous shared chat session permalink

### ISSUE THREAD

**Issue by dmelo89** [gitbito/bitoai#222]
I am using bito.ai in VSCode.

When I click 'share' the bito.ai extension creates a share.bito.ai link, this link is acessible to anyone who has the link. 

We don't have options to make it private or delete it. When I delete a previous session in VSCode extension it doesn't delete the shared chat session permalink, as I checked its still functional even if delete is confirmed and chat session is gone from the extension. 

This should be fixed ASAP because it's a potential privacy and security risk, if someone unintentionally shares some code and later cannot remove it.

**Comment by bitoandy** [comment]
@dmelo89 , thanks for the feedback, we will work on getting this fixed and providing permalink controls.

**Comment by dmelo89** [comment]
> @dmelo89 , thanks for the feedback, we will work on getting this fixed and providing permalink controls.

Thanks for the reply.

Additionally I wanted to request to delete a session I have shared accidently in the past, can you help me with that? I have no people in my team and I didn't want my session to be stored in share.bito.ai

I've sent a message to support but got no answer yet.

**Comment by nisha-bito** [comment]
Hi @dmelo89 ,

Please share the link that needs to be deleted. You can send email on support@bito.ai and we will delete it for you. 

Thanks,
Nisha
