### ISSUE TITLE
Port settings for remote connect

### ISSUE THREAD

**Issue by lemonade7296** [gitbito/bitoai#226]
![image](https://github.com/user-attachments/assets/a39a1227-6687-47b6-b5df-dc27e30fefd2)
Each time I connect to the same remote host, I'm prompted to enter a port number, which is temporary and changes every time. Setting the port repeatedly is a bit tedious. Is there any way to configure a permanent port for each remote host? Any guidance would be greatly appreciated!

**Comment by nisha-bito** [comment]
hi @lemonade7296 ,

For now each time the VS code is restarted this step is required. 
However, we will internally evaluate if we can add some workaround to avoid it. 

Thanks,
Nisha

**Comment by lemonade7296** [comment]
@nisha-bito I’m really looking forward to it, and thanks again!
