### ISSUE TITLE
Unable to login in 2023.1

### ISSUE THREAD

**Issue by gozus19p** [gitbito/bitoai#25]
Hi. First, thanks for your great product.
I am opening this issue because I am unable to prompt in my e-mail in Bito window. I am using IntelliJ IDEA Ultimate 2023.1 on Linux Mint (with new UI).
Steps to reproduce:
1. open Bito plugin;
2. set the focus on the e-mail input;
3. try to digit something... Nothing happens.
Let me know if I can give you further details. I am not writing a negative review for this, anyway.

**Comment by bitoandy** [comment]
Thanks @gozus19p for reporting this. We are looking into the issue using the steps mentioned. Will let you know if we need more information.

**Comment by nisha-bito** [comment]
hi @gozus19p ,

We analyzed and found that all flavor of Linux has the same issue on the version 2023.1. Where in any input box in plugin is not showing typed character while copy and paste works fine.  We have also validated this on few more IntelliJ plugins and same issue exists in all. 
We are working with JetBrains team for this issue.  And we shall update you with any progress on this. 

Thanks,
Nisha

**Comment by gozus19p** [comment]
Hi,

thank you so much for your commitment.

Have a nice day

**Comment by nisha-bito** [comment]
hi @gozus19p ,

JetBrains team has provided a workaround to solve this issue.
The fix should be be available with Bito's next release. We shall update you once we release the next build. 

Thanks,
Nisha

**Comment by bitoandy** [comment]
Hi @gozus19p ,
The fix for this will be available in version 1.0.134 which is currently in review with JetBrains team and should be available in next 24 to 48 hours on the marketplace for download/install/update.

**Comment by gozus19p** [comment]
Hi,

I've downloaded the fixed version. It works like a charm!

Thank you again for your work and your commitment.

Have a nice day,
Manuel
