### ISSUE TITLE
Custom shortcut commands

### ISSUE THREAD

**Issue by 1JayPeng** [gitbito/bitoai#27]
### **Why not let developers customize shortcut commands in the settings**
I need to Chinese comments but bito only has English comments by default, and when I modify ask it doesn't call pycharm's comparison view
![image](https://user-images.githubusercontent.com/42126564/228791616-1d1a57d1-65cd-423c-b268-4d337e7a06c7.png)
![image](https://user-images.githubusercontent.com/42126564/228791705-510790f9-e77d-4366-b02d-e8e955231741.png)
![image](https://user-images.githubusercontent.com/42126564/228791736-34dc8a09-88da-4f78-b586-e64e0272bbad.png)

**Comment by monicfenga** [comment]
你得用汉语跟她说，比如“使代码在中文中更易读，并重写代码”

另外，“chinease”拼错了，是“Chinese”

-----

You have to say to her in Chinese.

Also, "chinease" is misspelled as "Chinese"

**Comment by monicfenga** [comment]
我个人的使用方式是，先在文本框里用汉语写好要做的事，然后粘贴代码过去，一并发送

**Comment by 1JayPeng** [comment]
谢谢，我正是这样做的，而事实上我是希望能够更加自由的定制化属于自己的bito

**Comment by bitomukesh** [comment]
custom shortcut is in product roadmap. should be out shortly.

**Comment by bitomukesh** [comment]
closing this as we have added it in our roadmap.
