### ISSUE TITLE
Typo in "Delete this sesion"

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#28]
Well... just look at it:

![Delete this season](https://user-images.githubusercontent.com/39868412/229748593-416e3ffd-cca3-4188-bab3-8534680241a2.PNG)

the title "Delete this sesion"has a typo, description is fine.

**Comment by bitoandy** [comment]
Hi @monicfenga , ouch, thanks for sending the screen shot, we will fix it in the next release

**Comment by nisha-bito** [comment]
hi @monicfenga ,

This correction is done in Bito 1.0.134. thanks again for reporting this. 

Thanks,
Nisha
