### ISSUE TITLE
Clarify data flow and data protection policy

### ISSUE THREAD

**Issue by stefaneidelloth** [gitbito/bitoai#29]
If I send a query with bitoai, is the data then passed on to openai.com?

OpenAI is allowed to combine the personal data with the queries and us that for many purposes. The amount of privilages is that high that one should users should expect that their data will be publicly available. 

Is this the same when using bitoai? Where can I find the data protection policy of bitoai?

**Comment by amargoel98** [comment]
Hi, we do pass your requests, including code in your requests (like "Explain this Code") to OpenAI.  However, our agreement with OpenAI states that they do not store your code or use your code for training or improving their models.  We use Google Analytics on our website to help us understand things like what pages on our site are being visited, but we do not use Google Analytics in the IDE extension or in our application. So Google Analytics does not have access to your code.  We try and keep your code as secure as possible.  I hope this helps.
