### ISSUE TITLE
[Enhancement] Create custom shortcuts

### ISSUE THREAD

**Issue by ulrickpsp** [gitbito/bitoai#3]
It will be really helpful for me to create my custom shortcuts to use in the code.

For example:

"Comment this code following Dart best practices for documentation"

**Comment by bitomukesh** [comment]
Thanks for the feedback. We have added it to our roadmap. You can check the progress here
https://bito.canny.io/feature-requests/p/custom-shortcuts

**Comment by nisha-bito** [comment]
hi @ulrickpsp ,

Bito version 1.0.135 version is release with new feature to support Custom Templates, which allows you to create a custom shortcut. 
Please try the new feature and let us know if this meets your requirement. 

Please note: this ticket will be closed, please feel free to open a new ticket for any new feedback/issues. 

Thanks,
Nisha
