### ISSUE TITLE
Does bitoai support PyCharm Community Edition?

### ISSUE THREAD

**Issue by stefaneidelloth** [gitbito/bitoai#30]
It says "Installed" but I do not see the corresponding window on the right side, even after restart.

![image](https://user-images.githubusercontent.com/12675339/230158974-8167d96b-4215-49d1-9d02-3d7e0667e888.png)

**Comment by stefaneidelloth** [comment]
After another try I got the message

Bito: Attention Required: Please enable JCEF browser by enabling settings as per below.

![image](https://user-images.githubusercontent.com/12675339/230159934-536b0f63-2c67-45aa-a97b-caa927b9a1a4.png)

Sounds scary.

=> Can you please adapt bitoai to work with the default runtime?

**Comment by nisha-bito** [comment]
hi @stefaneidelloth ,

Based on what version of Java you are using, you will get multiple options to select from the Runtime environment which supports JCEF browser. You may want to try to select a different option to make it work. 

Example - 
![image](https://github.com/gitbito/bitoai/assets/123052606/ffae5781-c4e8-46b4-b82d-17bef1020083)

Can you help us with below information in order for us to replicate the issue - 
1. IDE version 
2. Java version 
3. Operating System 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @stefaneidelloth ,

Can you please confirm if the above suggestion works for you.
This ticket will be closed soon. you can always re-open this ticket or create a new one if required. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @stefaneidelloth ,

Closing this ticket, however you can always re-open the ticket or create a new ticket if you face any further issue.

Thanks,
Nisha
