### ISSUE TITLE
【FEAT】Re-log in when open other vscode window

### ISSUE THREAD

**Issue by lismill** [gitbito/bitoai#32]
Remember the account for a fixed time

**Comment by dzcpy** [comment]
How are you able to use it, I mean through a proxy?

**Comment by lismill** [comment]
no proxy
1. open a vscode window
2. use an email to log in to the system using a 6-digit verification code
3. open another vscode window
4. click the plug-in icon. The message "You need to log in again" is displayed. 
5. return to the first window, the permission error is displayed.

**Comment by bitoandy** [comment]
Hi @lismill ,

Thanks for the steps to reproduce the issue, we are looking into this and will provide an update once its fixed.

**Comment by lismill** [comment]
thanks
