### ISSUE TITLE
Making textbox in bito resizable

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#33]
Sometimes I need to get Bito to generate a function to meet my requirements, and I need a lot of words to describe my requirements and test cases, but the text box in the Bito interface is too small (only about 2 to 5 lines of visible space, and you can't scroll with the mouse, only with the arrow keys), so I usually create a file, write the requirements, select them all and copy them, then paste them into the Bito text box. I don't think it's that efficient in some ways.

It would be easier (for me to write requirements in Bito) if the text box was resizable, or if I could add a 'maximize' button so that the text box takes up the full size of the Bito window when clicked.

![text box is too small](https://user-images.githubusercontent.com/39868412/230753284-0bc34c0e-85e7-4c2c-a880-86692f65ecd9.png)

**Comment by bitomukesh** [comment]
Hi, thanks for reporting. We are checking why it;s not scrollable with mouse. thanks for the feedback,

**Comment by monicfenga** [comment]
I have now established that there are four states of the text box:
- The text box is short
- The text box is tall
- The text box is scrollable (with scroll bars)
- The text box is not scrollable (no scroll bar)
These states are randomly paired with two other states, such as "the text box is tall and cannot be scrolled" or "the text box is short and can be scrolled"
&nbsp;


Geticer
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mukesh ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gitbito/bitoai] Making textbox in bito resizable (Issue #33)





 
Hi, thanks for reporting. We are checking why it;s not scrollable with mouse. thanks for the feedback,

**Comment by nisha-bito** [comment]
hi @monicfenga ,

Thanks for reporting this. We will analyze these at our end.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @monicfenga ,

We have done some fixes in the text area and considered your concern and suggestions as well. Please use Bito version 1.0.135 and let us know your feedback. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @monicfenga ,

Please let us know if you have any feedback on the modification done on text area. 
This ticket will be closed shortly if the concerns are resolved. 

Thanks,
Nisha

**Comment by bitomukesh** [comment]
we are also looking at something like maximizing and pinning the text box. this has been added to the roadmap. https://github.com/orgs/gitbito/projects/1

**Comment by monicfenga** [comment]
> hi @monicfenga ,
> 
> We have done some fixes in the text area and considered your concern and suggestions as well. Please use Bito version 1.0.135 and let us know your feedback.
> 
> Thanks, Nisha

it's better now.

sorry for the late reply.

**Comment by nisha-bito** [comment]
thanks @monicfenga .

Looking forward for more suggestions :)  [if any].

Thanks,
Nisha
