### ISSUE TITLE
installed yeterday. no gpt4.

### ISSUE THREAD

**Issue by stjema** [gitbito/bitoai#34]

**Comment by bitomukesh** [comment]
Hi, we use Turbo 3.5 for smaller prompts and GPT for longer prompts. If you ask the Bito AI, it will say GPT 3 as the prompt is small and routed to Turbo 3.5.

**Comment by stjema** [comment]
the ai should tell the user if its 4 or 3.5.

**Comment by bitomukesh** [comment]
@stjema - GPT will always respond by saying it uses GPT 3, even when using GPT 3.5. 

![image](https://user-images.githubusercontent.com/86046840/232051527-33a9d13f-03a9-4fa0-9e8e-d0054e53720f.png)

We only route to GPT 4 for long prompts, so it's unlikely that you will be able to get a response from AI that it uses GPT 4.

**Comment by bitomukesh** [comment]
Here is an example of asking what version of GPT to GPT-4 model, and it doesn't handle the prompt well. 

![image](https://user-images.githubusercontent.com/86046840/232052410-9f971c8b-9bf6-4fdc-aa78-0964616eb5e4.png)

**Comment by bestK** [comment]
`We only route to GPT 4 for long prompts` ? I always got `Reached token limit, please try again by reducing AI input`
