### ISSUE TITLE
Cannot type Chinese in the input field

### ISSUE THREAD

**Issue by Summer-LL** [gitbito/bitoai#35]
After updating PyCharm, I  can't type Chinese in the input field，only can English.
MacBook Pro M1 macOS :ventura 13.0.1
PyCharm: PyCharm 2023.1 (Professional Edition)
Bito: 1.0.133
Looking forward to you answer!

**Comment by nisha-bito** [comment]
hi @Summer-LL ,

We will analyze the reported issue. Thanks for the input.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
Great to hear @Summer-LL .
