### ISSUE TITLE
In VSCode,How can I easily reference code from local files ?

### ISSUE THREAD

**Issue by dongly** [gitbito/bitoai#36]
Now I can only achieve this by copying and pasting

**Comment by bitomukesh** [comment]
Hi, for now, you can select any code and use any of the shortcuts like explain code, etc. We will be adding the ability to add custom shortcuts in the upcoming release, and will also make it easy to reference existing code with your own prompts.

**Comment by nisha-bito** [comment]
Hi all,

Template feature is released via Bito 1.0.135 version, which gives you a way to create custom prompts. Please do use the feature and let us know if this meets the requirement. 

This ticket/issue will be closed now, please feel free to create a new ticket if you need any further info/help.

Thanks,
Nisha
