### ISSUE TITLE
Allow Custom Questions in addition to predefined shortcuts for selected code.

### ISSUE THREAD

**Issue by Rageus** [gitbito/bitoai#37]
Currently I only have limited amount of predefined options available to perform an operation on selected code.

![jgPh7ellI6RKKzCn](https://user-images.githubusercontent.com/37166914/233094604-e84d39d4-f7e9-4e16-94fa-b62336827f9a.png)

From what I can see all of what these shortcuts do is: copying the code, insert a hardcoded question into chat gpt, then pasting the code.
It would be nice to have a way to alter that hardcoded question either on the fly with an input field prompt (what I would prefer) or by allowing to add custom questions.

**Comment by nisha-bito** [comment]
hi @Rageus ,

Thanks for the suggestion.
This is there in our road map. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Rageus ,

We have introduced "Template"  feature with Bito 1.0.0135 version, where you can create your own custom prompts by specifying your own questions/prompts. Please do use the feature and let us know if this meets your requirement ? 

Thanks,
Nisha

**Comment by Rageus** [comment]
Hey, @nisha-bito 
I tired out the new feature for adding templates on version 1.0.135 and here is my feedback:
- creating, editing, deleting templates work fine and the query results also make sense.
- unfortunately there is no way to add keyboard shortcuts to custom templates and they also don't appear in the "Bito AI" (and clicking it is quite cumbersome)
![Unity_72fvVX9peyqquTLa](https://user-images.githubusercontent.com/37166914/236837297-b24aeb1a-5f1c-4a2e-83d2-a9f3b4d9adda.png) maybe we can still support this?

**Comment by nisha-bito** [comment]
hi @Rageus ,

Thanks for the feedback. This is there in our roadmap and should be coming soon. 

Thanks,
Nisha

**Comment by bitomukesh** [comment]
Closing this issue.
