### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by CarlosShao** [gitbito/bitoai#40]
Why doesn't it work on Idea?

**Comment by nisha-bito** [comment]
hi @CarlosShao ,

Sorry to hear that its not working for you.
Can you help us understand what error you are getting ? Also please share the information below to understand the issue you are facing and suggest you a fix - 
1. OS 
2. Which idea and what version 
3. What error you are facing ? [login, AI request  or something else ? ]

**Comment by nisha-bito** [comment]
hi @CarlosShao,

We had an issue on our end which might have created login issues The issue is resolved now.
Please try to login again and do let us know if you face any further issues. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @CarlosShao ,

we haven't heard from you in a while. Do you still need help?

We will close this issue shortly if this issue is resolved.

Thanks,
Nisha
