### ISSUE TITLE
it always redirect to the login page

### ISSUE THREAD

**Issue by zzzwjZhang** [gitbito/bitoai#42]
when i login on it first time,it guide me to create my workspace,then it goes to the login page , or when i join the
workspace i created before,it redirect to the login page again ,wtf?

**Comment by bitoandy** [comment]
Hi @zzzwjZhang ,

We have identified the issue on our end and we are working on getting the fix live in next couple of hours to solve this issue.
Will notify once the fix is live. Regret the inconvenience.

**Comment by nisha-bito** [comment]
Hi @zzzwjZhang , 

The issue related to Login is resolved and the fix is deployed. Please do let us know if you face any further issues. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @zzzwjZhang ,

We haven't heard from you in a while. Do you still need help?

We will close this issue shortly if this issue is resolved.

Thanks,
Nisha
