### ISSUE TITLE
The latest version of Android Studio and java 17 doesn't work

### ISSUE THREAD

**Issue by SenLuoVientiane** [gitbito/bitoai#44]
The latest version of Android Studio and java 17 doesn't work
received error：
Please enable JCEF browser by enabling settings as per below. 
1. Go to Help -> Find action 
2. Type -> 'Choose Boot Java Runtime for the IDE'. 
3. From the dropdown 'New', select a Boot runtime which support JCEF browser. 
4. Select ok and restart.

**Comment by nisha-bito** [comment]
hi @SenLuoVientiane ,

Bito uses JCEF browser and JCEF browser support is not enabled by default in Android studio. And thus you need to enable JCEF browser manually. The steps can guide you to enable the settings. 

Hope this works for you.

Thanks,
Nisha

**Comment by SenLuoVientiane** [comment]
This problem still occurs after manually enabling the JCEF browser

-Djcef.browser.enable=true

**Comment by SenLuoVientiane** [comment]
Android Studio Flamingo | 2022.2.1
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    de.ax.powermode (102.201)
    GsonFormatPlus (1.6.1)
    cn.yiiguxing.plugin.translate (3.4.2)

**Comment by nisha-bito** [comment]
hi @SenLuoVientiane ,

Please select below version for Java 17 ,
![image](https://github.com/gitbito/bitoai/assets/123052606/e8231185-f6d9-406d-b5b8-8c7bfa272099)

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @SenLuoVientiane ,

Please confirm if the solution suggested works for you ? 
This ticket will be closed soon, you can always re-open the ticket or create a new one in case needed. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @SenLuoVientiane ,

Closing this ticket, however you can always re-open the ticket or create a new ticket if you face any further issue.

Thanks,
Nisha

**Comment by Sumit258000** [comment]
After changing Boot Runtime to above make Android Studio super slow. @nisha-bito

**Comment by RTException** [comment]
but, I attempted to change the runtime of Android Studio Jellyfish (2023.3.1 Patch 1) to a version that supports JCEF (e.g., jbr_jcef-17.0.10-osx-aarch64-b1087.23), but after the modification, Android Studio crashed upon restart.
