### ISSUE TITLE
It doesn't work well on AndroidStudio 2022.2.1

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [gitbito/bitoai#45]
The runtime of jcef for java17 has been selected 
Still report an error
![image](https://user-images.githubusercontent.com/62411322/234795880-d0378567-2cf6-4c87-82d8-fa4bcf3fcfe5.png)
![image](https://user-images.githubusercontent.com/62411322/234795988-60272c96-70f9-40e7-ab47-6d3c84725ed0.png)

**Comment by XiaoRanLiu3119** [comment]
Registry jecf enabled
![image](https://user-images.githubusercontent.com/62411322/234796366-293d424d-26b7-4601-ad50-def8c788ac28.png)

**Comment by nisha-bito** [comment]
hi @XiaoRanLiu3119 ,

Try to select a diff version form the list and check. 
Below highlighted version works, you may want to try this ?
![image](https://github.com/gitbito/bitoai/assets/123052606/99c7e3ed-2ea3-4b51-8077-89279c904a7a)

Thanks,
Nisha

**Comment by XiaoRanLiu3119** [comment]
I tried,but i con't download that 'fastdebug' , don't know why.
Then i reselect this
![image](https://github.com/gitbito/bitoai/assets/62411322/a156ece5-b301-49c7-a007-535424e2b5e5)

and i update the bito,it worked! 
Thanks alot.
