### ISSUE TITLE
In IDEA2021, Bito version 1.0.134 has a logon timeout problem, and it still doesn't log in after sending the authentication code several times

### ISSUE THREAD

**Issue by youngStarlit** [gitbito/bitoai#46]
In IDEA2021, Bito version 1.0.134 has a logon timeout problem, and it still doesn't log in after sending the authentication code several times.
After the logon time-out, the looping icon is hidden. Once again, you can click the submit button.At this point click on the following exception.
![image](https://user-images.githubusercontent.com/83155642/235043586-033c912c-8566-46e9-b520-e66ae29e2977.png)

**Comment by nisha-bito** [comment]
hi @youngStarlit ,

Sorry about this.  We have been having some capacity issues as many users are signing up.  We are working to fix this, and hope to have this addressed in the next 12 hours or so.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @youngStarlit ,

Can you please try to login again. The issue with login is resolved and you should be able to login successfully. 
Please let us know if you face any further issues. 

Thanks,
Nisha

**Comment by bitoandy** [comment]
Thanks @youngStarlit for confirming.
