### ISSUE TITLE
Is any plan to support Neovim ?

### ISSUE THREAD

**Issue by 3Xpl0it3r** [gitbito/bitoai#47]
Describe as title, this product is very good, but is doesn't support vim/nvim.
So Is any plan to write plugin to support Neovim  or expose some api ?

**Comment by bitoandy** [comment]
Hi @3Xpl0it3r ,

Currently we are supporting VS Code and JetBrains IDEs.
We do have Bito CLI which can be used to implement a VIM plugin for Bito. We are working on adding context file support to Bito CLI that should help if anyone planning on building VIM plugin.
We will see if we can add it to our roadmap and keep you posted.

**Comment by zhenyangze** [comment]
Hope this can help you：
https://github.com/zhenyangze/vim-bitoai

**Comment by bitoandy** [comment]
Thanks @zhenyangze for sharing the VIM plugin. Let us know if we can add it to Bito CLI README so that folks wanting VIM plugin can use it?

**Comment by zhenyangze** [comment]
> Thanks @zhenyangze for sharing the VIM plugin. Let us know if we can add it to Bito CLI README so that folks wanting VIM plugin can use it?

That would be an honor

**Comment by 3Xpl0it3r** [comment]
@zhenyangze thx

**Comment by bitoandy** [comment]
@zhenyangze , checkout https://github.com/orgs/gitbito/discussions/70. Let us know what you think.
Would love to have you participate.
Also can you share your email, by sending us an email on founders@bito.ai?
