### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by jghuangcn** [gitbito/bitoai#49]
The comments can be translated into other language by using Bit AI

**Comment by bitoandy** [comment]
Hi @jghuangcn , we are working on adding settings to set the output language for Bito AI, this should help with translating.
Let us know if you are thinking of some more in terms of functionality

**Comment by monicfenga** [comment]
you can ask bito to do it, like "Please translate the comment to (your language)"

or just use your language to ask bito

**Comment by monicfenga** [comment]
@bitoandy I think this issue can be closed

**Comment by bitoandy** [comment]
Thanks @monicfenga , closing the issue.
