### ISSUE TITLE
好用

### ISSUE THREAD

**Issue by CarlosShao** [gitbito/bitoai#54]
作为一个免费插件， 真的是完爆别的插件， 当然， 除了龟速和频繁的超时
但是它免费啊， 还要什么自行车？而且还有上下文关联， 我用的某些收费的垃圾都没这功能

**Comment by llplay** [comment]
好奇能免费多久

**Comment by nisha-bito** [comment]
Thank you for reaching out to us.
We are working on to address the speed issue.

Separately, we are working on putting together a paid version and are trying to get some opinions from users. We will have a free version, but it will probably have limits to daily and monthly use and also not be prioritized for fast service. Between
1) understanding your local code and including that in query results,
2) use of GPT-4,
3) custom prompts you can create, and
4) CLI access,
which of these features are most valuable to you? What would be a price you feel would start to become expensive to pay for Bito on a monthly basis?

**Comment by monicfenga** [comment]
> 好奇能免费多久

按照bito的说法，付费版主要面向企业用户

**Comment by nisha-bito** [comment]
hi @CarlosShao ,

Do you still face issue with slowness and frequent timeout ?
Please confirm if we can close this issue now ? 

Thanks,
Nisha
