### ISSUE TITLE
sign up failed

### ISSUE THREAD

**Issue by hapenguc** [gitbito/bitoai#57]
1. I tried to sign up using my email 
![image](https://github.com/gitbito/bitoai/assets/52886368/67c24986-edc4-469e-9af5-1b10a048de5d)

2. after I  typed my email and pressed continue, the page was like this and doesn't work\refresh.
![image](https://github.com/gitbito/bitoai/assets/52886368/675ffe0e-25cf-42d1-b261-be7c4afedeea)
3 when I double click the right bottom part of this picture, the whole window disappear and nothing happens

**Comment by hapenguc** [comment]
idea version: 2022.1
os: window 10

**Comment by bitomukesh** [comment]
thanks, we are looking at this.

**Comment by nisha-bito** [comment]
hi @hapenguc ,

Can you help us with the screenshot of the error message which is displayed ? 
Also please confirm if you are using java8 in your idea ? 

Thanks,
Nisha

**Comment by wmzy** [comment]
The error:
```sh
Access to XMLHttpRequest at 'https://mgmtapi.bito.co/api/token' from origin 'vscode-webview://154i3qd5c1eaigcstmtb98nohdieqq6rrtnn47utb1bdh71f7gpa' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

**Comment by nisha-bito** [comment]
hi @wmzy ,

please confirm if you are using java8 in your idea ?

Thanks,
Nisha

**Comment by wmzy** [comment]
@nisha-bito I using Visual Studio Code:
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No

**Comment by nisha-bito** [comment]
hi @wmzy 

Can you confirm which Bito version you are using on VS code? 
Also please try to install the latest version of Bito 1.0.137 and let us know if this resolves your problem ? 

If problem still exists, can you give screenshot of the issues and error form logs? 

Thanks,
Nisha

**Comment by wmzy** [comment]
@nisha-bito  problem still exists on version 1.0.137 :
![image](https://github.com/gitbito/bitoai/assets/5526525/07497444-dc4f-4987-a4d2-e79ddc446873)

**Comment by nisha-bito** [comment]
hi @wmzy ,

Can you please if there is an Anti-Virus/firewall  - if any you are using which is blocking these request ?

**Comment by bitoandy** [comment]
Hi @wmzy ,

We wanted to check if there is something on the network side blocking you access. 
Can you check if https://alpha.bito.ai is accessible from browser on your machine and let us know. This will help us debug quickly.

**Comment by wmzy** [comment]
@bitoandy Yes, it is assessible.

**Comment by wmzy** [comment]
@nisha-bito Sorry, my English is not very good.

**Comment by hapenguc** [comment]
> hi @hapenguc ,
> 
> Can you help us with the screenshot of the error message which is displayed ? Also please confirm if you are using java8 in your idea ?
> 
> Thanks, Nisha

I tried  dragging the popup window i.e the error info using my mouse , but it didn't move.  so I can't see the error info

**Comment by hapenguc** [comment]
> @nisha-bito problem still exists on version 1.0.137 : ![image](https://user-images.githubusercontent.com/5526525/240609183-07497444-dc4f-4987-a4d2-e79ddc446873.png)

hi  ,     how did you get these error info in the right part?  press f12?

**Comment by hapenguc** [comment]
guys I just solved the problem by setting proxy, appreciate for your help

**Comment by nisha-bito** [comment]
@hapenguc : Glad to hear it. Feel free to reach out to us if you face any further issues .
