### ISSUE TITLE
If you select the history session, the login is cleared and you need to log in again

### ISSUE THREAD

**Issue by Vampire-DIO** [gitbito/bitoai#60]
one step
![image](https://github.com/gitbito/bitoai/assets/48446966/bca8a6a2-5f9f-4bcd-a194-894710d19471)

two
![image](https://github.com/gitbito/bitoai/assets/48446966/359f02f6-d5f6-44a8-a247-0ef7aeb1a03d)

three
If the text is incorrect, the login information will be cleared and you need to log in again

**Comment by monicfenga** [comment]
u can try the following steps:
1. Reopen vscode and open bito
2. Press the gear icon and select "Logout"
3. Login again

**Comment by Vampire-DIO** [comment]
thank your reply
