### ISSUE TITLE
A message is displayed indicating that the session expires, but the login fails

### ISSUE THREAD

**Issue by CarlosShao** [gitbito/bitoai#61]
![0a2303574ab94c0ec3b0a29af210cc6](https://github.com/gitbito/bitoai/assets/35945730/38870234-1c3c-4162-a3c2-ed4c35875f1d)
Error message: Your session has expired, please login again.

**Comment by bitomukesh** [comment]
thanks for reporting this. we are investigating.

**Comment by CarlosShao** [comment]
It's a pity that today still can't be connected





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitbito/bitoai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月16日(星期二) 晚上6:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitbito/bitoai] A message is displayed indicating that the session expires, but the login fails (Issue #61)





 
thanks for reporting this. we are investigating.

**Comment by monicfenga** [comment]
Try the following steps:
1. After opening the bito window, first click the gear icon and select "Logout"
2. Then log in again

**Comment by CarlosShao** [comment]
> Try the following steps:
> 
> 1. After opening the bito window, first click the gear icon and select "Logout"
> 2. Then log in again
It still doesn't work

**Comment by bitoandy** [comment]
@CarlosShao , @monicfenga ,

Some of our servers serving requests became inaccessible, causing this issue. We are working on bringing the services back up.
Will notify once the service is back up completely, we are currently at 30% of capacity should be back up to 100% of our capacity in sometime.

**Comment by monicfenga** [comment]
> Some of our servers serving requests became inaccessible, causing this issue...


![3](https://github.com/gitbito/bitoai/assets/39868412/e8accb11-76f0-45a1-b091-ac523eae8508)

**Comment by CarlosShao** [comment]
> @CarlosShao , @monicfenga ,
> 
> Some of our servers serving requests became inaccessible, causing this issue. We are working on bringing the services back up. Will notify once the service is back up completely, we are currently at 30% of capacity should be back up to 100% of our capacity in sometime.

I got it.

**Comment by bitoandy** [comment]
Hi @CarlosShao , @monicfenga ,

The services is back up. We are monitoring to check for any further issues. You should now be able to receive output for your queries.
