### ISSUE TITLE
Repeatedly prompting "connection timeout"

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#63]
Today, when I try to ask bito any question, the following prompt is sure to appear:

> Whoops, looks your request is timing out. …… Sorry for any inconvenience. Please try again a little later.

I have tried so far:

- Restarting vscode
- Logging back into my account
- Rebooting the router

It does not improve the problem either.

What information should I give to you for the analysis of the problem?

**Comment by bitoandy** [comment]
Hi @monicfenga, thanks for notifying, we are looking into this issue. We will get back to you once we identify the cause and fix.

**Comment by SaNkiRyo** [comment]
I have the same problem

**Comment by bitoandy** [comment]
Hi @SaNkiRyo , @monicfenga ,

Some of our servers serving requests became inaccessible, causing this issue. We are working on bringing the services back up.
Will notify once the service is back up completely, we are currently at 30% of capacity should be back up to 100% of our capacity in sometime.

**Comment by monicfenga** [comment]
> Some of our servers serving requests became inaccessible, causing this issue.

![3](https://github.com/gitbito/bitoai/assets/39868412/cea7bbd8-de46-40c5-a3a8-1ee550540228)

**Comment by gaoxiaoen** [comment]
Thank your offering, if ok, tell me ,I think bito is a good code assistants!

**Comment by bitoandy** [comment]
The services is back up. We are monitoring to check for any further issues. You should now be able to receive output for your queries.

**Comment by gaoxiaoen** [comment]
I test is OK! thank U!

**Comment by bitoandy** [comment]
@monicfenga , check out https://github.com/orgs/gitbito/discussions/70 , let us know what you think, would be great to have you participate

**Comment by monkeyshichi** [comment]
Today, when I try to ask bito any question, the following prompt is sure to appear:

Whoops, looks your request is timing out. …… Sorry for any inconvenience. Please try again a little later.

please tell me how to solve

**Comment by bitoandy** [comment]
Hi @monkeyshichi ,

We are looking into this issue on our end. Can you restart your IDE and let us know if it's working. Also let us know the version of IDE extension for Bito that you are using and the OS.
