### ISSUE TITLE
gpt4?

### ISSUE THREAD

**Issue by Minh-X** [gitbito/bitoai#64]
![image](https://github.com/gitbito/bitoai/assets/120098547/fa57ab26-8f76-4ab5-afec-6ca61f706f77)

![image](https://github.com/gitbito/bitoai/assets/120098547/75a9d925-b2fb-4ffe-b122-f21b61a32d20)

**Comment by bitoandy** [comment]
Hi @Minh-X ,

Given below are responses from OpenAI GPT-4 itself.
<img width="1223" alt="Screenshot 2023-05-17 at 8 30 52 AM" src="https://github.com/gitbito/bitoai/assets/125080245/840bcded-20d1-40e4-b6ae-7b5e16fc8981">
<img width="1028" alt="Screenshot 2023-05-17 at 8 32 29 AM" src="https://github.com/gitbito/bitoai/assets/125080245/de1d0c71-67ec-4c65-a1f0-68d4d16bb810">
Hope this helps resolve your query.
