### ISSUE TITLE
Can not sign up

### ISSUE THREAD

**Issue by bowencool** [gitbito/bitoai#65]
I got an error "Please enter a valid email address":
<img width="284" alt="image" src="https://github.com/gitbito/bitoai/assets/20217146/dcc977ce-25f2-42c1-bd05-40c32072d47b">

**Comment by nisha-bito** [comment]
hi @bowencool ,

Thanks for reporting this, we will fix it in next release. 

Thanks,
Nisha

**Comment by bitoandy** [comment]
@bowencool , This issue has been fixed in the latest version 1.0.137 available both on VSCode as well as JetBrains extension marketplace.. Please check and let us know if you face any issues.

**Comment by bowencool** [comment]
It works, thank you.
