### ISSUE TITLE
jetbrains' plugin version

### ISSUE THREAD

**Issue by marsman123** [gitbito/bitoai#66]
jetbrains' plugin version is only 1.0.135,when it will be updated to 136?

**Comment by nisha-bito** [comment]
hi @marsman123 ,

It's under verification and will be available soon.

Thanks,
Nisha

**Comment by bitoandy** [comment]
@marsman123 , the latest version 1.0.137 is now available on the JetBrains marketplace: https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4--free-ai-assistant-for-developers/versions

**Comment by marsman123** [comment]
> @marsman123 , the latest version 1.0.137 is now available on the JetBrains marketplace: https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4--free-ai-assistant-for-developers/versions

thanks
