### ISSUE TITLE
How to set the font size of the Bito panel in Visual Studio Code?

### ISSUE THREAD

**Issue by bisslot** [gitbito/bitoai#71]
The font size in Bito panel is different fro
m that in Visual Studio Code IDE. How can I change the font size of Bito panel?

![QQ截图20230526205155](https://github.com/gitbito/bitoai/assets/2107614/62c5f28e-5813-45be-8903-3588ebffac52)

**Comment by nisha-bito** [comment]
hi @bisslot ,

The font size in Bito panel is taken dynamically from the VS code. 

In case you want to change the font size of Bito, you can change is by VS code font size via -> File -> Preference -> Settings -> Text Editor -> Font -> change the font size you want to use in Bito. 
Please note: after font change, Bito needs to be restarted once to reflect the change. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @bisslot ,

Let us know this solves your concerns and if this ticket can be closed now. 

Thanks,
Nisha

**Comment by bisslot** [comment]
Thank you very much!
