### ISSUE TITLE
can't register in IDEA

### ISSUE THREAD

**Issue by naah69** [gitbito/bitoai#72]
<img width="718" alt="image" src="https://github.com/gitbito/bitoai/assets/25682169/16fee86c-9f6d-44bc-9ae6-07c536550579">

**Comment by nisha-bito** [comment]
hi @naah69 ,

Please share more info -
1. OS you are using 
2. IDE name and IDE version 
3. Bito Version 
4. logs - Help-> open Logs in Explorer -> share idea.log 
5. Console log -> Help -> Find Action -> Type "Bito open dev tool". Go to console -> filter on errors -> an share screenshot fo the errors. 
![image](https://github.com/gitbito/bitoai/assets/123052606/13c852c4-4b74-484f-9df9-0fec28724ce7)


Thanks,
Nisha

**Comment by zhuangbinan** [comment]
Same issue.

IntelliJ IDEA 2021.2.2

![image](https://github.com/gitbito/bitoai/assets/34266962/671964d2-a150-4f45-9c59-f11cee4193fe)

**Comment by nisha-bito** [comment]
hi @naah69 ,

Can you please check if there is an Anti-Virus/firewall - if any you are using which is blocking these request ?
Can you try to set proxy and check again ? 

Thanks,
Nisha

**Comment by zhuangbinan** [comment]
I am setting a local proxy like this picture:
![image](https://github.com/gitbito/bitoai/assets/34266962/ffd0bcfb-33df-480e-8d1e-06ee042cefee)

This setting will make bito not work properly, even if I set *.jetbrains.com,*.bito.co,*.bito.ai

When I choose No proxy , bito can work just fine. 
![image](https://github.com/gitbito/bitoai/assets/34266962/35696fcc-b0a0-459a-aed5-65aedfc2855e)

**Comment by nisha-bito** [comment]
try to use No proxy for http://ideapp/ && https://ideapp/

**Comment by naah69** [comment]
I had configurated them for `no proxy`,but it still don't work.

<img width="871" alt="image" src="https://github.com/gitbito/bitoai/assets/25682169/afab308a-a778-48e7-9615-99bf99ad0a28">

![image](https://github.com/gitbito/bitoai/assets/25682169/2a19dbdc-208f-4c5c-a4f2-218512836c89)

**Comment by yunximing** [comment]
改成 这个代理 http://ideapp/, https://ideapp/ 使用梯子再登录一下就可以了

**Comment by nisha-bito** [comment]
hi @yunximing ,

Are you able to use Bito now with above settings ? 

Thanks,
Nisha

**Comment by naah69** [comment]
> 

no,it still don't work.

<img width="717" alt="image" src="https://github.com/gitbito/bitoai/assets/25682169/f665c365-3500-4c7c-808c-2d6156c0b51a">

**Comment by nisha-bito** [comment]
hi @naah69 ,

Please use no proxy to use Bito plugin inside IDE.

Thanks,
Nisha
