### ISSUE TITLE
To use BITO on VS Code running on SSH, please refer [link] to forward port 2511 on SSH 

### ISSUE THREAD

**Issue by theone-pang** [gitbito/bitoai#73]
tip: To use BITO on VS Code running on SSH, please refer [link] to forward port 2511 on SSH 
how resolve this question

**Comment by nisha-bito** [comment]
hi @theone-pang ,

Please find more info and a loom video on how to configure SSH. 
1. VS Code Tutorial for SSH: https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks 
2. loom video to configure BITO with SSH: https://www.loom.com/share/88279fb89ee345fdb2943707ca84c364

Hope this will help you. Please contact us if you face any further issue. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @theone-pang ,

Let us know if you are able to configure SSH and use it now ? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @theone-pang ,

Please try the suggested way to configure SSH and let us know if you face any further issue. 
This ticket will closed soon, you can always re-open the ticket or create a ticket if required. 

Thanks,
Nisha

**Comment by sparkEchooo** [comment]
I set the forwarding port to 39995, and it works.
:)

**Comment by nisha-bito** [comment]
thanks for confirming.
