### ISSUE TITLE
the bito plugin can't open

### ISSUE THREAD

**Issue by playmaker** [gitbito/bitoai#74]
Type: <b>Bug</b>

# click the bito button on the left plugin bar. no response and always loading. but the bito cli works fine.

Extension version: 1.0.137
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 7a1f2dcc-50d0-4b66-b7e1-611f272cc07f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by nisha-bito** [comment]
hi @playmaker .

Can you please open Help -> Toggle Developer tool. and keep the filer on console -> errors. And send us the screen shot ? 
![image](https://github.com/gitbito/bitoai/assets/123052606/a21bb9a7-d6d1-4127-a2f8-497a86435860)

Thanks,
Nisha

**Comment by playmaker** [comment]
> hi @playmaker .
> 
> Can you please open Help -> Toggle Developer tool. and keep the filer on console -> errors. And send us the screen shot ? ![image](https://user-images.githubusercontent.com/123052606/241717220-a21bb9a7-d6d1-4127-a2f8-497a86435860.png)
> 
> Thanks, Nisha
I got no errors but 1 warning message. Is there anyting to useful to solve the problem?
![图片](https://github.com/gitbito/bitoai/assets/4124950/1a80e847-ffb5-4fdc-aa84-392f7bea31f0)
![图片](https://github.com/gitbito/bitoai/assets/4124950/dca8a31e-301a-4ed5-b651-b0fcc54b84cb)

**Comment by nisha-bito** [comment]
hi @playmaker ,

Can you try to follow below steps - 
1. restart your VS code.
2. open Developer tools first 
3. then click on Bito icon from left panel
This will show some logs in the console or in network tab. Currently there is no info/error related to bito is loaded in console. 

thank you for your help in analyzing the issue. 

Thanks,
Nisha

**Comment by playmaker** [comment]
> hi @playmaker ,
> 
> Can you try to follow below steps -
> 
>     1. restart your VS code.
> 
>     2. open Developer tools first
> 
>     3. then click on Bito icon from left panel
>        This will show some logs in the console or in network tab. Currently there is no info/error related to bito is loaded in console.
> 
> 
> thank you for your help in analyzing the issue.
> 
> Thanks, Nisha

Thanks for your reply. I followed your steps, and it looks like no errors about the bito. This is the screenshot
![图片](https://github.com/gitbito/bitoai/assets/4124950/a80c3f7f-aefb-4f2b-93ab-d6dd92e4b08a)

**Comment by nisha-bito** [comment]
hi @playmaker ,

Is it possible for you to connect over a short call to debug the issue ? Let us know convenient time. 

Thanks,
Nisha

**Comment by Ray0401** [comment]
I have the same question


<img width="1714" alt="image" src="https://github.com/gitbito/bitoai/assets/29241464/777dfdcb-8ad7-44ab-b4ea-01de4a31842a">

**Comment by nisha-bito** [comment]
hi @Ray0401 ,

Are you also using Darwin  ?

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Ray0401 ,

Is it possible to connect over a small call to analyze the issue ? Let us know a convenient time. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Ray0401 ,

In absense of any response this issue will be closed. Please feel free to create a new issue or re-open same in case you face any further issue with Bito.

Thanks,
Nisha

**Comment by yildirimsamet** [comment]
@nisha-bito 
same for me, macos
![image](https://github.com/gitbito/bitoai/assets/73336471/73eec715-84f7-4ab1-8cc1-2e59ed8a71f5)

**Comment by nisha-bito** [comment]
hi @yildirimsamet ,

Can you please try to clear cached data folder and then re-start Visual Studio Code. Cache data can be found at below location. 


Windows: <user-home-directory>\\AppData\\Roaming\\Code
macOS: $HOME/Library/Application Support/Code
Linux: $HOME/.config/Code

Thanks,
Nisha

**Comment by yildirimsamet** [comment]
still same :(
first version of bito is working but giving version error
![image](https://github.com/gitbito/bitoai/assets/73336471/0b10eeda-5f9e-4156-afa8-ba2891ed7fac)

**Comment by nisha-bito** [comment]
hi @yildirimsamet ,

Can you remove the extension and then search the Bito again from the Extension list to ensure, you are installing the latest version which is 1.2.7 from marketplace. 
Can you let us know the email you are using for logging into Bito ?

Thanks,
Nisha
