### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by taojiangcb** [gitbito/bitoai#77]
it doesn't work see the bottom have a red box.  I don't understand.![image](https://github.com/gitbito/bitoai/assets/1563529/a21f5e36-6fb3-436e-830a-52b1bb58b070)

**Comment by nisha-bito** [comment]
hi @taojiangcb ,

Can you help us with some more informaiton in order for us to analyze the issue - 
1. Bito version 
2. OS
3. VS code version 
4. open Help -> Toggle Developer tool. and keep the filter on console -> errors. And send us the screen shot ?
5. Open Help -> Toggle Developer tool -> Network tab. And send us the screenshot. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @taojiangcb ,

Additionally can you please check if there is an Anti-Virus/firewall - if any you are using which is blocking these request ?
Can you try to set proxy and check again ?

Thanks,
Nisha

**Comment by yunximing** [comment]
I can't login
Bito version：1.0.138
idea:2023.1.2(Ultimate Edition)
OS：Windows 10 专业版 22H2

**Comment by bobveg** [comment]
I have the same problem. I'm on Manjaro linux. I have no antivirus or any active proxy.

**Comment by nisha-bito** [comment]
hi @bobveg ,

Can you please provide below information - 

1. Bito version
2. OS
3. VS code version
4. open Help -> Toggle Developer tool. and keep the filter on console -> errors. And send us the screen shot ?
5. Open Help -> Toggle Developer tool -> Network tab. And send us the screenshot.

Thanks,
Nisha

**Comment by taojiangcb** [comment]
sorry, i'm come in be late, but I had logined it
