### ISSUE TITLE
连续两天，大约从下午01:00开始无法与Bito对话 For two days in a row, I cant talk to Bito from about 01:00 pm onwards

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#81]
> 时间以北京时间为准。

如题。但是过几个小时（大约到下午03:00至06:00）后就可以使用了。

估计是Bito在睡觉？

-----------

> Times are based on China standard time(UTC+8).

As the title suggests. But after a few hours (until about `03:00 pm` to `06:00 pm`) it works again.

Guess Bito is sleeping? If that's the case, wish her a good night's(or any time of the day) sleep.

**Comment by bitoandy** [comment]
@monicfenga , we had server issues for last 2 days during the time period mentioned. We have added a few fixes to avoid issues. 
Also we are seeing "model overloaded with other requests" issues from OpenAI which we are working with them, which will take time as its their infra related task.

**Comment by monicfenga** [comment]
![I get it](https://github.com/gitbito/bitoai/assets/39868412/4f6784aa-72a4-430e-a753-15616b9c8986)

**Comment by monicfenga** [comment]
It is now 05:10pm and bito is available

![](https://github.com/gitbito/bitoai/assets/39868412/c62339b6-4de6-4cbe-8030-32c68c444dc9)
