### ISSUE TITLE
Bito Website issue 2x

### ISSUE THREAD

**Issue by monicfenga** [gitbito/bitoai#84]
### Where

Any blog page, like this one: https://bito.ai/11-language-frameworks-you-may-have-not-heard-of-that-could-double-your-income/

### 1. unordered list's dot is inside the text, and covered a little bit of text

![PHP is the best choice for you](https://github.com/gitbito/bitoai/assets/39868412/a0005df4-3fcc-4f34-98a8-b4a15253daab)

### 2. double subscribe?

![subscribe and subscribe](https://github.com/gitbito/bitoai/assets/39868412/ee7c3e60-07d6-4ace-ab7d-0157706c8bef)

**Comment by bitoandy** [comment]
Thanks @monicfenga for letting us know about the issue, we are working on fixing it

**Comment by nisha-bito** [comment]
hi @monicfenga ,

Thanks for reporting the issue. They are resolved now. 
Appreciate your help.

Thanks,
Nisha
