### ISSUE TITLE
Bito AI extension doesn't allow the different email format than what is allowed on website

### ISSUE THREAD

**Issue by iamsank8** [gitbito/bitoai#85]
I signed up with an email 'xyz+bito@abc.com' but when I tried to login with same email on VSCode extension, its not allowing it.
<img width="529" alt="image" src="https://github.com/gitbito/bitoai/assets/24712341/a0aae995-2aef-40eb-898c-7c7fc5736a70">

**Comment by nisha-bito** [comment]
hi @iamsank8 ,

We will analyze the issue and add a fix for the same.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @iamsank8 ,

The fix for above will be available in next Bito release which is expected to be release in early next week. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @iamsank8 ,

Please down latest version of Bito plugin for the fix. 

Thanks,
Nisha

**Comment by bitoandy** [comment]
Hi @iamsank8 ,

Let us know if you were able to use your email ID with the latest version of Bito.

**Comment by iamsank8** [comment]
I am able to use the email ID. Thank you :)
