### ISSUE TITLE
bito cant open with Android Studio Flamingo

### ISSUE THREAD

**Issue by wisdomtl** [gitbito/bitoai#87]
I do choose boot runtime for IDE with the version 17.0.6  and restart the IDE, still cant open bito (In windows, mac os is ok)

**Comment by nisha-bito** [comment]
hi @wisdomtl ,

you can try to choose alternative boot runtime environment which support JCEF browser. 
![image](https://github.com/gitbito/bitoai/assets/123052606/bda2f4c7-8acd-4424-91ff-7d183e6471f2)


Thanks,
Nisha

**Comment by amargoel98** [comment]
Hi, please check out this article: https://docs.bito.ai/support-and-questions/troubleshooting

**Comment by nisha-bito** [comment]
hi @wisdomtl ,

Please note, this ticket will be auto closed in few days, please feel free to create a new ticket in case the problem still exists. 

Thanks,
Nisha
