### ISSUE TITLE
Regular expressions cannot be displayed

### ISSUE THREAD

**Issue by hwl0123** [gitbito/bitoai#89]
Version: ChatGPT GPT-4 v1.1.0
Description: When I ask the following question: Use javascript to get the regular expression of the relative path file name
The following questions then arise, I posted two pictures for your reference, One is being generated, and one is generating the result.
![image](https://github.com/gitbito/bitoai/assets/20965363/b1c03f85-92b4-4a9e-9e0b-32eb5d3ee215)
![image](https://github.com/gitbito/bitoai/assets/20965363/de298f20-0b36-4960-851c-e313dfee48bd)

**Comment by bitoandy** [comment]
Hi @hwl0123 ,
There is an issue on our end while parsing and printing the result, causing this issue. We are working on fixing this and will update once the fix is available.

**Comment by hwl0123** [comment]
> 



> hi @hwl0123 ,
> 
> Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.
> 
> Thanks, Nisha

Thanks for your job
