### ISSUE TITLE
Can't input Chinese word with android studio.

### ISSUE THREAD

**Issue by huangxuchu** [gitbito/bitoai#90]

**Comment by nisha-bito** [comment]
hi @huangxuchu ,

We are looking into the issue and the fix shall be available with next Bito release. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @huangxuchu ,

Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @huangxuchu ,

Version 1.1.2 is available on marketplace, can you please install and let us know if the fix is working for you.
Please note, this ticket will be auto closed in few days, please feel free to create a new ticket in case the problem still exists. 

Thanks,
Nisha
