### ISSUE TITLE
Japanese IME Issue - JetBrains plugin

### ISSUE THREAD

**Issue by york-yarmt** [gitbito/bitoai#92]
When I attempt to input Japanese using the Japanese IME (Input Method Editor), the conversion window (selection of candidates) appears in an inappropriate position, and only English alphabets are output in the input field. As a result, I'm unable to input Japanese.

<img width="1512" alt="image" src="https://github.com/gitbito/bitoai/assets/98591947/c153bc65-dd2f-48ef-a315-a7778f2cd10a">

**Comment by bitoandy** [comment]
Hi @york-yarmt ,

We are looking into the issue and will update once we analyze the issue and identify the fix.

**Comment by nisha-bito** [comment]
hi @york-yarmt ,

Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @york-yarmt ,

Version 1.1.2 is also available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha
