### ISSUE TITLE
Bito AI Public API

### ISSUE THREAD

**Issue by abdfnx** [gitbito/bitoai#93]
Hi @gitbito, I think if bito make a public api for people, this would be a great thing.

Thank you for your time.

**Comment by Plutowzz2539** [comment]
> I need it, too. I would like pay for this😊

I want to use bito in my bot. That's excited.🎉

**Comment by bitoandy** [comment]
Hi @abdfnx , @Plutowzz2539 ,

Thanks for the request for the API. Would you be open to a call with our product team, we would like to understand the needs to better API design.
cc @bitomukesh

**Comment by abdfnx** [comment]
> Hi @abdfnx , @Plutowzz2539 ,
> 
> Thanks for the request for the API. Would you be open to a call with our product team, we would like to understand the needs to better API design. cc @bitomukesh

Hi @bitoandy, well, we just need an api to fetch responses from your cool bitoai api, and I think you need to create a website or service to create **API Keys** for that.

The nice request body is like this

```json
{
   "prompt": "Generate a deno server code"
}
```

And Of Course, the headers will be like this

**Authorization**: `btai-********************`

That is my suggestion 🤝.

Thank you for your time.

**Comment by abdfnx** [comment]
Any Progress @bitoandy @bitomukesh ?

**Comment by bitomukesh** [comment]
Hi, thanks for checking back. Releasing the Bito public API is not in our short-term roadmap. However, if we see interest from many users, we may consider it.
