### ISSUE TITLE
Can't input Chinese word with IntelliJ IDEA.

### ISSUE THREAD

**Issue by ATATAATT** [gitbito/bitoai#94]

**Comment by bitoandy** [comment]
hi @ATATAATT ,

We are looking into this issue and will update once we have the fix identified.

**Comment by nisha-bito** [comment]
hi @ATATAATT ,

Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @ATATAATT ,

Version 1.1.2 is also available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha
