### ISSUE TITLE
After updating the latest version, Chinese cannot be entered in the input box and deletion operations cannot be performed

### ISSUE THREAD

**Issue by ThankyouEverybody** [gitbito/bitoai#96]

**Comment by nisha-bito** [comment]
hi @ThankyouEverybody 

We are looking into the issue and the fix shall be available with next Bito release. 

Thanks,
Nisha

**Comment by irodger** [comment]
Hey folks! 
The same problem with Bito.ai plugin for Webstorm with russian input and backspace won't work. 

Thanks for your job. Waiting for the fix

**Comment by bitoandy** [comment]
In the interim to go back to the previous version, you can do following:

Uninstall current version of Bito.
Download the previous version from URL: https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4/versions
After downloading install by going to plugins and using "Install Plugin from Disk" option and selecting the downloaded version.
![Screenshot 2023-06-24 at 9 28 54 AM](https://github.com/gitbito/bitoai/assets/125080245/b8057ac8-fb9d-4a86-aa12-4b84b4fb342d)

We are working on fixing this issue with the next update to the extension

**Comment by nisha-bito** [comment]
hi @ThankyouEverybody , @irodger ,

Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha

**Comment by irodger** [comment]
> hi @ThankyouEverybody , @irodger ,
> 
> Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.
> 
> Thanks, Nisha

Hi, Nisha! 

it works. Thank you. 
Very useful ai, using it everyday. Good job, folks!

**Comment by ThankyouEverybody** [comment]
> hi @ThankyouEverybody , @irodger ,
> 
> Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.
> 
> Thanks, Nisha

The problem has been fixed. Thank you very much
