### ISSUE TITLE
更新到1.1.0版本无法输入中文,无法使用快捷键复制文本

### ISSUE THREAD

**Issue by dear2021888** [gitbito/bitoai#97]
WebStorm 2023.1.2 
mac系统
1. 无法输入中文
2.无法使用快捷键复制文本;
bug表现为: 按下任何修饰按键会自动聚焦到输入框;  (command, option)

**Comment by nisha-bito** [comment]
hi @dear2021888 

We are looking into the issue and the fix shall be available with next Bito release. 

Thanks,
Nisha

**Comment by dvxiaofan** [comment]
我也是WebStorm 2023.1.2，目前同样无法输入中文，只能外面编辑好文字，粘贴进来

**Comment by nisha-bito** [comment]
hi @dvxiaofan and @dear2021888  ,

A bug got introduced in version 1.1.0 which we are working on fixing in the next release of the extension.
In the interim to go back to the previous version, you can do following:

Uninstall current version of Bito.
Download the previous version from URL: https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4/versions
After downloading install by going to plugins and using "Install Plugin from Disk" option and selecting the downloaded version.
Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @dvxiaofan  and @dear2021888 ,

Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha
