### ISSUE TITLE
There is a problem with the member deactivation function

### ISSUE THREAD

**Issue by ouzhijian** [gitbito/bitoai#98]

**Comment by nisha-bito** [comment]
hi @ouzhijian ,

Can you please provide more details on the issue -
1. What error you are getting ? 
2. Can you provide email address and sued and workspace name. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @ouzhijian ,

Gentle reminder to send information on the error encountered? 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @ouzhijian ,

Please help us with the required input for us to debug issue further. Please note, in absence of the input, this ticket will be closed after few days. You can always create a new ticket if the error persists. 

Thanks,
Nisha
