### ISSUE TITLE
1.1.0版本

### ISSUE THREAD

**Issue by slm998** [gitbito/bitoai#99]
无法输入中文，
输错的信息无法删除
请问什么时候修复好

**Comment by nisha-bito** [comment]
hi @slm998 ,

A bug got introduced in version 1.1.0 which we are working on fixing in the next release of the extension.
In the interim to go back to the previous version, you can do following:
- Uninstall current version of Bito.
- Download the previous version from URL: https://plugins.jetbrains.com/plugin/18289-chatgpt-gpt-4/versions
- After downloading install by going to plugins and using "Install Plugin from Disk" option and selecting the downloaded version.

Thanks,
Nisha

**Comment by slm998** [comment]
ok ok Please fix the bug quickly

**Comment by bitoandy** [comment]
The extension version with the bug fix is currently under review in JetBrains marketplace expected to be available for update on JetBrains marketplace soon.

**Comment by nisha-bito** [comment]
hi @slm998 ,

Version 1.1.1 is available on marketplace, can you please install and let us know if the fix is working for you.

Thanks,
Nisha

**Comment by slm998** [comment]
ok thanks
